-- Add multi-level approval statuses to ErpDocumentStatus enum
ALTER TYPE "ErpDocumentStatus" ADD VALUE IF NOT EXISTS 'APPROVE_1' AFTER 'NEED_APPROVE';
ALTER TYPE "ErpDocumentStatus" ADD VALUE IF NOT EXISTS 'APPROVE_2' AFTER 'APPROVE_1';
ALTER TYPE "ErpDocumentStatus" ADD VALUE IF NOT EXISTS 'APPROVE_3' AFTER 'APPROVE_2';
ALTER TYPE "ErpDocumentStatus" ADD VALUE IF NOT EXISTS 'APPROVE_4' AFTER 'APPROVE_3';
