insert into m_12_lp_detail(
SELECT
0 as idlpdetail,
295 as idlp,
i.bid as idbarang,
i.bsatuan as satuan,
i.bnilaisatuan as nilaisatuan,
i.bsatuan as satuanbarang,
'IDR' as matauang,
1 as kurs,
i.bhargabeli as hargabeli,
IFNULL(((pi.pihargajual1 - i.bhargabeli) / i.bhargabeli) * 100,0) as margin1,
IFNULL(((pi.pihargajual2 - i.bhargabeli) / i.bhargabeli) * 100,0) as margin2,
IFNULL(((pi.pihargajual3 - i.bhargabeli) / i.bhargabeli) * 100,0) as margin3,
IFNULL(((pi.pihargajual4 - i.bhargabeli) / i.bhargabeli) * 100,0) as margin4,
IFNULL(((pi.pihargajual5 - i.bhargabeli) / i.bhargabeli) * 100,0) as margin5,
pi.pihargajual1 as hargajual1lama,
pi.pihargajual2 as hargajual2lama,
pi.pihargajual3 as hargajual3lama,
pi.pihargajual4 as hargajual4lama,
pi.pihargajual5 as hargajual5lama,
pi.pihargajual1 as hargajual1,
pi.pihargajual2 as hargajual2,
pi.pihargajual3 as hargajual3,
pi.pihargajual4 as hargajual4,
pi.pihargajual5 as hargajual5,
pi.pidiskonjual1 as diskonjual1lama,
pi.pidiskonjual2 as diskonjual2lama,
pi.pidiskonjual3 as diskonjual3lama,
pi.pidiskonjual4 as diskonjual4lama,
pi.pidiskonjual5 as diskonjual5lama,
pi.pidiskonjual1 as diskonjual1,
pi.pidiskonjual2 as diskonjual2,
pi.pidiskonjual3 as diskonjual3,
pi.pidiskonjual4 as diskonjual4,
pi.pidiskonjual5 as diskonjual5,
pi.pistokminimal as stokminimallama,
pi.pistokmaksimal as stokmaksimallama,
pi.pistokreorder as stokreorderlama,
pi.pistokminorder as stokminorderlama,
pi.pistokminimal as stokminimal,
pi.pistokmaksimal as stokmaksimal,
pi.pistokreorder as stokreorder,
pi.pistokminorder as stokminorder,
'' as cabang,
'' as lokasi,
'' as gudang,
'' as costcenter,
'' as divisi,
'' as subdivisi,
'' as proyek,
'' as catatan,
@urut := @urut + 1 as urutan,
'0' as statusberlaku,
'0' as idppadetail,
'0' as isclose,
'' as customtext1,
'' as customtext2,
'' as customtext3,
'0' as customdbl1,
'0' as customdbl2,
'0' as customdbl3,
'1900-01-01' as customdate1,
'1900-01-01' as customdate2,
'1900-01-01' as customdate3
FROM
m_12_pos_item pi
JOIN m1_item i ON pi.pikategori = 'GL' AND pi.piidbarang = i.bid,
(SELECT @urut := 0) AS variableInit1 
)