/**
 * Mock data + formatting helpers — ported from prototype `data.jsx`.
 * Typed TS exports; no `window.*` globals (the prototype attached these
 * to `window`, here they are real module exports).
 */

export function fmtIDR(n: number): string {
  const neg = n < 0;
  const v = Math.abs(n).toLocaleString('id-ID', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return (neg ? '-' : '') + v;
}

export function fmtCompact(n: number): string {
  if (Math.abs(n) >= 1e9) return `${(n / 1e9).toFixed(2)}M`;
  if (Math.abs(n) >= 1e6) return `${(n / 1e6).toFixed(1)}jt`;
  if (Math.abs(n) >= 1e3) return `${(n / 1e3).toFixed(0)}rb`;
  return String(n);
}

export const todayStr = '12/05/2026';

export const CABANGS = ['PCI', 'JKT', 'BDG', 'SBY'] as const;
export const LOKASIS = [
  'T - FG',
  'T - RM',
  'T - WIP',
  'PCI - Gudang',
  'JKT - Gudang',
] as const;
export const USERS = ['rania', 'fitri.h', 'rendra', 'maya.p', 'budi.t'] as const;
export const STATUSES = [
  'Approved',
  'Need Approve',
  'Posted',
  'Draft',
  'Rejected',
] as const;

const TERIMA_DARI = [
  'PT Sumber Rejeki',
  'CV Cahaya Abadi',
  'PT Mitra Sentosa',
  'Toko Berkah Jaya',
  'PT Karya Mandiri',
  'CV Tirta Makmur',
  'PT Indo Lestari',
  'Kasir Cabang PCI',
  'Kasir Cabang JKT',
  'PT Global Niaga',
  'CV Anugerah',
  'Pelanggan Tunai',
];

const URAIAN_KAS = [
  'Pembayaran invoice INV-2026',
  'Setoran kas harian',
  'Penerimaan DP order',
  'Pelunasan piutang',
  'Penjualan tunai',
  'Refund supplier',
  'Transfer antar kas',
  'Setoran modal',
];

const rng = (seed: number): (() => number) => {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) >>> 0;
    return s / 4294967296;
  };
};

export interface KasMasukRow {
  id: number;
  no: string;
  tanggal: string;
  terimaDari: string;
  total: number;
  status: string;
  uraian: string;
  lokasi: string;
  cabang: string;
  user: string;
  uang: string;
}

export function genKasMasuk(n = 64): KasMasukRow[] {
  const r = rng(42);
  return Array.from({ length: n }, (_, i): KasMasukRow => {
    const day = Math.floor(r() * 12) + 1;
    const month = 5;
    const year = 2026;
    const total = Math.round((r() * 24500000 + 250000) / 1000) * 1000;
    return {
      id: i + 1,
      no: `CR-26${String(month).padStart(2, '0')}-${String(2400 - i).padStart(4, '0')}`,
      tanggal: `${String(day).padStart(2, '0')}/${String(month).padStart(2, '0')}/${year}`,
      terimaDari: TERIMA_DARI[Math.floor(r() * TERIMA_DARI.length)],
      total,
      status: STATUSES[Math.floor(r() * STATUSES.length)],
      uraian: URAIAN_KAS[Math.floor(r() * URAIAN_KAS.length)],
      lokasi: LOKASIS[Math.floor(r() * LOKASIS.length)],
      cabang: CABANGS[Math.floor(r() * CABANGS.length)],
      user: USERS[Math.floor(r() * USERS.length)],
      uang: 'IDR',
    };
  });
}

export type ActivityType = 'success' | 'info' | 'danger' | 'warn';

export interface ActivityRow {
  who: string;
  what: string;
  target: string;
  amount: number | null;
  type: ActivityType;
  ts: string;
}

export const ACTIVITY: ActivityRow[] = [
  { who: 'fitri.h', what: 'memposting', target: 'CR-2605-2398', amount: 4250000, type: 'success', ts: '10:42' },
  { who: 'rendra', what: 'membuat draft', target: 'SM-2605-1182', amount: -1850000, type: 'info', ts: '10:31' },
  { who: 'rania', what: 'menyetujui', target: 'RM-2605-0871', amount: 12500000, type: 'success', ts: '10:14' },
  { who: 'maya.p', what: 'menolak', target: 'CD-2605-1640', amount: -3200000, type: 'danger', ts: '09:58' },
  { who: 'budi.t', what: 'meng-edit', target: 'GJ-2605-0412', amount: null, type: 'warn', ts: '09:47' },
  { who: 'fitri.h', what: 'memposting', target: 'CR-2605-2397', amount: 8750000, type: 'success', ts: '09:31' },
  { who: 'rendra', what: 'membatalkan', target: 'RG-2605-0231', amount: null, type: 'danger', ts: '09:12' },
  { who: 'rania', what: 'menyimpan', target: 'CB-2605-0019', amount: null, type: 'info', ts: '08:58' },
];

export const KPI_SERIES = {
  kasMasuk: [42, 48, 51, 39, 58, 62, 71, 65, 78, 82, 76, 91, 88, 95],
  kasKeluar: [33, 41, 38, 44, 49, 47, 52, 55, 51, 58, 61, 57, 63, 60],
  bankMasuk: [120, 134, 128, 142, 159, 161, 175, 168, 182, 196, 188, 211, 224, 219],
  giro: [12, 14, 11, 16, 18, 15, 19, 21, 18, 22, 25, 23, 27, 24],
} as const;

type Lang = 'id' | 'en' | 'ja';

const I18N: Record<Lang, Record<string, string>> = {
  id: {
    Dashboard: 'Dashboard',
    Statistik: 'Statistik',
    'Data Master': 'Data Master',
    Keuangan: 'Keuangan',
    Transaksi: 'Transaksi',
    Laporan: 'Laporan',
    Persediaan: 'Persediaan',
    Pembelian: 'Pembelian',
    Sales: 'Sales',
    Produksi: 'Produksi',
    'Fixed Asset': 'Fixed Asset',
    Setting: 'Setting',
    'Kas Masuk': 'Kas Masuk',
    'Kas Keluar': 'Kas Keluar',
    'Bank Masuk': 'Bank Masuk',
    'Bank Keluar': 'Bank Keluar',
    'Jurnal Umum': 'Jurnal Umum',
    'Giro Masuk': 'Giro Masuk',
    'Giro Keluar': 'Giro Keluar',
    'Buku Besar': 'Buku Besar',
    Tambah: 'Tambah',
    'Cari semua...': 'Cari semua...',
    'Pendapatan bulan ini': 'Pendapatan bulan ini',
    'Pengeluaran bulan ini': 'Pengeluaran bulan ini',
    'Saldo Bank': 'Saldo Bank',
    'Giro Outstanding': 'Giro Outstanding',
    'vs bulan lalu': 'vs bulan lalu',
    'Aktivitas Terbaru': 'Aktivitas Terbaru',
    'Lihat semua': 'Lihat semua',
    'Aksi Cepat': 'Aksi Cepat',
    Pintasan: 'Pintasan',
    'Buat Kas Masuk': 'Buat Kas Masuk',
    'Buat Kas Keluar': 'Buat Kas Keluar',
    'Posting Jurnal': 'Posting Jurnal',
    'Lihat Buku Besar': 'Lihat Buku Besar',
    'Cash Flow 14 Hari': 'Cash Flow 14 Hari',
    'Top Transaksi Hari Ini': 'Top Transaksi Hari Ini',
    Customer: 'Customer',
    Supplier: 'Supplier',
    Item: 'Item',
    'Chart of Account': 'Chart of Account',
    'Cabang & Lokasi': 'Cabang & Lokasi',
    'Cost Center': 'Cost Center',
    'Stock Opname': 'Stock Opname',
    'Mutasi Stok': 'Mutasi Stok',
    Penyesuaian: 'Penyesuaian',
    'Transfer Gudang': 'Transfer Gudang',
    'PO Pembelian': 'PO Pembelian',
    'Penerimaan Barang': 'Penerimaan Barang',
    'Faktur Pembelian': 'Faktur Pembelian',
    'Retur Pembelian': 'Retur Pembelian',
    'SO Penjualan': 'SO Penjualan',
    Pengiriman: 'Pengiriman',
    'Faktur Penjualan': 'Faktur Penjualan',
    'Retur Penjualan': 'Retur Penjualan',
    'Work Order': 'Work Order',
    BOM: 'BOM',
    'Output Produksi': 'Output Produksi',
    'Daftar Aset': 'Daftar Aset',
    Penyusutan: 'Penyusutan',
    Disposal: 'Disposal',
    Users: 'Users',
    Roles: 'Roles',
    Preferensi: 'Preferensi',
    Neraca: 'Neraca',
    'Laba Rugi': 'Laba Rugi',
    'Arus Kas': 'Arus Kas',
    'Perubahan Modal': 'Perubahan Modal',
    Tampilan: 'Tampilan',
    Notifikasi: 'Notifikasi',
    Aktivitas: 'Aktivitas',
    'Tutup tab': 'Tutup tab',
    'Tab baru': 'Tab baru',
    'Duplikat tab': 'Duplikat tab',
    'Muat ulang': 'Muat ulang',
    Tutup: 'Tutup',
    'Tutup tab lain': 'Tutup tab lain',
    'Tutup tab di kanan': 'Tutup tab di kanan',
    Administrator: 'Administrator',
    'Master Data': 'Master Data',
    'Finance & Accounting': 'Keuangan & Akuntansi',
    'Warehouse & Inventory': 'Gudang & Persediaan',
    Purchasing: 'Pembelian',
    Production: 'Produksi',
    'Fixed Assets': 'Aset Tetap',
    'Point of Sale': 'Point of Sale',
    'Point of Sales': 'Point of Sales',
    'HR & Payroll': 'HR & Payroll',
    Hospital: 'Rumah Sakit',
    Academic: 'Akademik',
    Cooperative: 'Koperasi',
    Settings: 'Setting',
    Appearance: 'Tampilan',
    'Profil Saya': 'Profil Saya',
    Keluar: 'Keluar',
    Division: 'Divisi',
    'Sub Division': 'Sub Divisi',
    Department: 'Departemen',
    'Sub Department': 'Sub Departemen',
    Project: 'Proyek',
    Branch: 'Cabang',
    Location: 'Lokasi',
    Warehouse: 'Gudang',
    Workspace: 'Workspace',
    'Buat Workspace': 'Buat Workspace',
    'Ganti workspace': 'Ganti workspace',
    'Hapus workspace': 'Hapus workspace',
    aktif: 'aktif',
    Aksi: 'Aksi',
    Navigasi: 'Navigasi',
    'Toggle dark mode': 'Toggle dark mode',
    'Switch language (ID/EN)': 'Ganti bahasa (ID/EN/JA)',
    // — list page / table / pagination —
    baris: 'baris',
    baru: 'baru',
    'Export data': 'Export data',
    Tampilkan: 'Tampilkan',
    'Jumlah baris per halaman': 'Jumlah baris per halaman',
    'Halaman pertama': 'Halaman pertama',
    'Halaman sebelumnya': 'Halaman sebelumnya',
    'Halaman berikutnya': 'Halaman berikutnya',
    'Halaman terakhir': 'Halaman terakhir',
    Filter: 'Filter',
    'Reset filter': 'Reset filter',
    dari: 'dari',
    'Memuat...': 'Memuat...',
    Kode: 'Kode',
    Status: 'Status',
    Aktif: 'Aktif',
    Nonaktif: 'Nonaktif',
    'Tidak ada hasil untuk filter ini': 'Tidak ada hasil untuk filter ini',
    'Tidak ada data': 'Tidak ada data',
    Riwayat: 'Riwayat',
    Aktifkan: 'Aktifkan',
    Nonaktifkan: 'Nonaktifkan',
    'baris dipilih': 'baris dipilih',
    'Menyimpan...': 'Menyimpan...',
    Simpan: 'Simpan',
    'Riwayat Perubahan': 'Riwayat Perubahan',
    'akan dihapus permanen.': 'akan dihapus permanen.',
    'yang dipilih akan dihapus permanen.': 'yang dipilih akan dihapus permanen.',
    'yang dipilih akan': 'yang dipilih akan',
    diaktifkan: 'diaktifkan',
    dinonaktifkan: 'dinonaktifkan',
    dibuat: 'dibuat',
    diperbarui: 'diperbarui',
    Gagal: 'Gagal',
    'Gagal menyimpan': 'Gagal menyimpan',
    'Export belum tersedia': 'Export belum tersedia',
    'Pilih semua': 'Pilih semua',
    'Pilih baris': 'Pilih baris',
    // — entity labels (used by simple-master-page) —
    'sub division': 'sub divisi',
    division: 'divisi',
    'sub departemen': 'sub departemen',
    departemen: 'departemen',
    project: 'proyek',
    'cost center': 'cost center',
    Konfirmasi: 'Konfirmasi',
    Batal: 'Batal',
    'Tutup tab?': 'Tutup tab?',
    'tab ini': 'tab ini',
    '"{label}" akan ditutup.': '"{label}" akan ditutup.',
    'Keyboard Shortcuts': 'Pintasan Keyboard',
    'Buka command palette': 'Buka command palette',
    'Tutup tab aktif': 'Tutup tab aktif',
    'Pindah ke tab 1–8': 'Pindah ke tab 1–8',
    'Pindah ke tab terakhir': 'Pindah ke tab terakhir',
    'Cycle bahasa ID/EN/JA': 'Cycle bahasa ID/EN/JA',
    'Tampilkan shortcut': 'Tampilkan shortcut',
    'Tutup overlay': 'Tutup overlay',
    'Command palette': 'Command palette',
    'Setujui dokumen terpilih?': 'Setujui dokumen terpilih?',
    'Tolak dokumen terpilih?': 'Tolak dokumen terpilih?',
    'Posting dokumen terpilih?': 'Posting dokumen terpilih?',
    'Hapus dokumen terpilih?': 'Hapus dokumen terpilih?',
    'Export data terpilih?': 'Export data terpilih?',
    Setujui: 'Setujui',
    Tolak: 'Tolak',
    Posting: 'Posting',
    Hapus: 'Hapus',
    disetujui: 'disetujui',
    ditolak: 'ditolak',
    diposting: 'diposting',
    dihapus: 'dihapus',
    diekspor: 'diekspor',
    'dokumen akan': 'dokumen akan',
    dokumen: 'dokumen',
    'Tindakan ini tidak dapat dibatalkan.': 'Tindakan ini tidak dapat dibatalkan.',
    'Aksi tercatat di audit trail.': 'Aksi tercatat di audit trail.',
    'belum dibaca': 'belum dibaca',
    'Tandai semua': 'Tandai semua',
    Semua: 'Semua',
    'Belum dibaca': 'Belum dibaca',
    'Tidak ada notifikasi': 'Tidak ada notifikasi',
    'Buka Dashboard': 'Buka Dashboard',
    'kejadian hari ini': 'kejadian hari ini',
    Sukses: 'Sukses',
    'Ditolak/Batal': 'Ditolak/Batal',
    Info: 'Info',
    Edit: 'Edit',
    'Tidak ada aktivitas': 'Tidak ada aktivitas',
    'Ketik perintah atau cari...': 'Ketik perintah atau cari...',
    'Tidak ada hasil': 'Tidak ada hasil',
    navigasi: 'navigasi',
    pilih: 'pilih',
    tutup: 'tutup',
    Reset: 'Reset',
    Tema: 'Tema',
    'Mode terang atau gelap': 'Mode terang atau gelap',
    'Mode Tema': 'Mode Tema',
    'Berlaku untuk seluruh aplikasi': 'Berlaku untuk seluruh aplikasi',
    Terang: 'Terang',
    Gelap: 'Gelap',
    Bahasa: 'Bahasa',
    Antarmuka: 'Antarmuka',
    Indonesia: 'Indonesia',
    English: 'Inggris',
    Japanese: 'Jepang',
    'Warna Aksen': 'Warna Aksen',
    'Paket & warna primer': 'Paket & warna primer',
    'Paket Warna': 'Paket Warna',
    'Set warna siap pakai': 'Set warna siap pakai',
    'Warna Spesifik': 'Warna Spesifik',
    'Aksen Aktif': 'Aksen Aktif',
    'Ukuran Font': 'Ukuran Font',
    'Skala teks antarmuka': 'Skala teks antarmuka',
    Ukuran: 'Ukuran',
    'Kecil · Normal · Besar · Ekstra Besar': 'Kecil · Normal · Besar · Ekstra Besar',
    Kecil: 'Kecil',
    Normal: 'Normal',
    Besar: 'Besar',
    'Ekstra Besar': 'Ekstra Besar',
    Pratinjau: 'Pratinjau',
    'Contoh teks tabel & form': 'Contoh teks tabel & form',
    Layout: 'Layout',
    'Kepadatan tampilan tabel & list': 'Kepadatan tampilan tabel & list',
    Kepadatan: 'Kepadatan',
    'Compact memuat lebih banyak baris': 'Compact memuat lebih banyak baris',
    Compact: 'Compact',
    Comfortable: 'Comfortable',
    'Menu Sidebar': 'Menu Sidebar',
    'Template navigasi samping': 'Template navigasi samping',
    Template: 'Template',
    'Ikon saja atau dengan label teks': 'Ikon saja atau dengan label teks',
    Ikon: 'Ikon',
    'Ikon + Label': 'Ikon + Label',
    'Setting · Tampilan': 'Setting · Tampilan',
    Tampilan_status: 'Tema {theme} · {primary} · font {fontScale} · {density} · sidebar {sidebar}',
    'Tampilan dikembalikan ke bawaan': 'Tampilan dikembalikan ke bawaan',
    'Gagal menyimpan preferensi tampilan': 'Gagal menyimpan preferensi tampilan',
    'Pratinjau Langsung': 'Pratinjau Langsung',
    'Perubahan diterapkan seketika': 'Perubahan diterapkan seketika',
    Export: 'Export',
    No: 'No',
    Nama: 'Nama',
    Total: 'Total',
    Korporat: 'Korporat',
    'Biru profesional': 'Biru profesional',
    Kreatif: 'Kreatif',
    'Violet & fuchsia': 'Violet & fuchsia',
    Natural: 'Natural',
    'Hijau segar': 'Hijau segar',
    Hangat: 'Hangat',
    'Amber & rose': 'Amber & rose',
    Biru: 'Biru',
    Indigo: 'Indigo',
    Violet: 'Violet',
    Fuchsia: 'Fuchsia',
    Rose: 'Rose',
    Amber: 'Amber',
    Emerald: 'Emerald',
    Teal: 'Teal',
    Cyan: 'Cyan',
    // --- Sidebar menu titles (seeded English → ID) ---
    'Initial Setup': 'Pengaturan Awal',
    Administration: 'Administrasi',
    System: 'Sistem',
    Organization: 'Organisasi',
    Items: 'Item',
    'Item Categories': 'Kategori Item',
    'Item Types': 'Tipe Item',
    Units: 'Satuan',
    'Item Locations': 'Lokasi Item',
    'Item Information': 'Informasi Item',
    'Product Class': 'Kelas Produk',
    'Price Index': 'Indeks Harga',
    'Price Category': 'Kategori Harga',
    Commission: 'Komisi',
    'Item Transaction Types': 'Tipe Penyesuaian Stok',
    'Stock Adjustment Type': 'Tipe Penyesuaian Stok',
    'Stock Adjustment Types': 'Tipe Penyesuaian Stok',
    'Item Permissions': 'Izin Item',
    Brand: 'Merek',
    Color: 'Warna',
    Size: 'Ukuran',
    Section: 'Seksi',
    Class: 'Kelas',
    'Sub Class': 'Sub Kelas',
    Model: 'Model',
    Designer: 'Desainer',
    Material: 'Material',
    Reference: 'Referensi',
    Vendor: 'Vendor',
    Miscellaneous: 'Lain-lain',
    'Customer Categories': 'Kategori Customer',
    'Supplier Categories': 'Kategori Supplier',
    'Partner Categories': 'Kategori Partner',
    Partners: 'Partner',
    'Salesman Categories': 'Kategori Salesman',
    Bank: 'Bank',
    Expedition: 'Ekspedisi',
    City: 'Kota',
    Province: 'Provinsi',
    Country: 'Negara',
    Currencies: 'Mata Uang',
    Taxes: 'Pajak',
    'Payment Terms': 'Termin Pembayaran',
    'Tax Settings': 'Pengaturan Pajak',
    'Document Numbering': 'Penomoran Dokumen',
    'Fiscal Periods': 'Periode Fiskal',
    'Approval Settings': 'Pengaturan Approval',
    'Audit Log': 'Log Audit',
    'Online Users': 'Pengguna Online',
    'User Log': 'Log Pengguna',
    'Close Fiscal Period': 'Tutup Periode Fiskal',
    'Recalculate COGS': 'Hitung Ulang HPP',
    'Repost Journals': 'Posting Ulang Jurnal',
    'Data Validity Check': 'Cek Validitas Data',
    'Menu Manager': 'Manajer Menu',
    'Settings Manager': 'Manajer Pengaturan',
    'Bank Accounts': 'Akun Bank',
    'Description Presets': 'Preset Deskripsi',
    'Format Settings': 'Pengaturan Format',
    'Default Settings': 'Pengaturan Bawaan',
    'Report Defaults': 'Bawaan Laporan',
    'Signature Settings': 'Pengaturan Tanda Tangan',
    Options: 'Opsi',
    'Home Layout': 'Layout Beranda',
    'Import Data': 'Impor Data',
    'Company Settings': 'Pengaturan Perusahaan',
    'Accounting Settings': 'Pengaturan Akuntansi',
    'User Management': 'Manajemen Pengguna',
    'Role Management': 'Manajemen Role',
    Permissions: 'Izin',
    Language: 'Bahasa',
    'Chart of Accounts': 'Bagan Akun',
    'Finance Masters': 'Master Keuangan',
    'AR Receipts': 'Penerimaan Piutang',
    'AP Payments': 'Pembayaran Utang',
    'Journal Entries': 'Jurnal',
    'General Ledger': 'Buku Besar',
    Giros: 'Giro',
    'Production Activity': 'Aktivitas Produksi',
    'Production Categories': 'Kategori Produksi',
    'Production Route': 'Rute Produksi',
    'Work Estimate': 'Estimasi Kerja',
    Labor: 'Tenaga Kerja',
    Machine: 'Mesin',
    'Other Costs': 'Biaya Lain',
    Transactions: 'Transaksi',
    Reports: 'Laporan',
    'Transaction Notes': 'Catatan Transaksi',
    'Txn Note Detail': 'Detail Catatan',
    Area: 'Area',
    'Point Categories': 'Kategori Poin',
  },
  en: {
    Dashboard: 'Dashboard',
    Statistik: 'Statistics',
    'Data Master': 'Master Data',
    Keuangan: 'Finance',
    Transaksi: 'Transactions',
    Laporan: 'Reports',
    Persediaan: 'Inventory',
    Pembelian: 'Purchasing',
    Sales: 'Sales',
    Produksi: 'Production',
    'Fixed Asset': 'Fixed Asset',
    Setting: 'Settings',
    'Kas Masuk': 'Cash Receipt',
    'Kas Keluar': 'Cash Disbursement',
    'Bank Masuk': 'Bank Receipt',
    'Bank Keluar': 'Bank Disbursement',
    'Jurnal Umum': 'General Journal',
    'Giro Masuk': 'Receivable Note',
    'Giro Keluar': 'Payable Note',
    'Buku Besar': 'General Ledger',
    Tambah: 'New',
    'Cari semua...': 'Search everything...',
    'Pendapatan bulan ini': 'Revenue MTD',
    'Pengeluaran bulan ini': 'Expense MTD',
    'Saldo Bank': 'Bank Balance',
    'Giro Outstanding': 'Notes Outstanding',
    'vs bulan lalu': 'vs last month',
    'Aktivitas Terbaru': 'Recent Activity',
    'Lihat semua': 'View all',
    'Aksi Cepat': 'Quick Actions',
    Pintasan: 'Shortcuts',
    'Buat Kas Masuk': 'New Cash Receipt',
    'Buat Kas Keluar': 'New Cash Disbursement',
    'Posting Jurnal': 'Post Journal',
    'Lihat Buku Besar': 'View Ledger',
    'Cash Flow 14 Hari': '14-Day Cash Flow',
    'Top Transaksi Hari Ini': 'Top Transactions Today',
    Customer: 'Customer',
    Supplier: 'Supplier',
    Item: 'Item',
    'Chart of Account': 'Chart of Account',
    'Cabang & Lokasi': 'Branch & Location',
    'Cost Center': 'Cost Center',
    'Stock Opname': 'Stock Take',
    'Mutasi Stok': 'Stock Movement',
    Penyesuaian: 'Adjustment',
    'Transfer Gudang': 'Warehouse Transfer',
    'PO Pembelian': 'Purchase Order',
    'Penerimaan Barang': 'Goods Receipt',
    'Faktur Pembelian': 'Purchase Invoice',
    'Retur Pembelian': 'Purchase Return',
    'SO Penjualan': 'Sales Order',
    Pengiriman: 'Delivery',
    'Faktur Penjualan': 'Sales Invoice',
    'Retur Penjualan': 'Sales Return',
    'Work Order': 'Work Order',
    BOM: 'BOM',
    'Output Produksi': 'Production Output',
    'Daftar Aset': 'Asset Register',
    Penyusutan: 'Depreciation',
    Disposal: 'Disposal',
    Users: 'Users',
    Roles: 'Roles',
    Preferensi: 'Preferences',
    Neraca: 'Balance Sheet',
    'Laba Rugi': 'Income Statement',
    'Arus Kas': 'Cash Flow',
    'Perubahan Modal': 'Equity Changes',
    Tampilan: 'Appearance',
    Notifikasi: 'Notifications',
    Aktivitas: 'Activity',
    'Tutup tab': 'Close tab',
    'Tab baru': 'New tab',
    'Duplikat tab': 'Duplicate tab',
    'Muat ulang': 'Reload',
    Tutup: 'Close',
    'Tutup tab lain': 'Close Other Tabs',
    'Tutup tab di kanan': 'Close Tabs to the Right',
    Administrator: 'Administrator',
    'Master Data': 'Master Data',
    'Finance & Accounting': 'Finance & Accounting',
    'Warehouse & Inventory': 'Warehouse & Inventory',
    Purchasing: 'Purchasing',
    Production: 'Production',
    'Fixed Assets': 'Fixed Assets',
    'Point of Sale': 'Point of Sale',
    'Point of Sales': 'Point of Sales',
    'HR & Payroll': 'HR & Payroll',
    Hospital: 'Hospital',
    Academic: 'Academic',
    Cooperative: 'Cooperative',
    Settings: 'Settings',
    Appearance: 'Appearance',
    'Profil Saya': 'My Profile',
    Keluar: 'Sign out',
    Division: 'Division',
    'Sub Division': 'Sub Division',
    Department: 'Department',
    'Sub Department': 'Sub Department',
    Project: 'Project',
    Branch: 'Branch',
    Location: 'Location',
    Warehouse: 'Warehouse',
    Workspace: 'Workspace',
    'Buat Workspace': 'New Workspace',
    'Ganti workspace': 'Switch workspace',
    'Hapus workspace': 'Delete workspace',
    aktif: 'active',
    Konfirmasi: 'Confirm',
    Batal: 'Cancel',
    'Tutup tab?': 'Close tab?',
    'tab ini': 'this tab',
    '"{label}" akan ditutup.': '"{label}" will be closed.',
    'Keyboard Shortcuts': 'Keyboard Shortcuts',
    'Buka command palette': 'Open command palette',
    'Tutup tab aktif': 'Close active tab',
    'Pindah ke tab 1–8': 'Switch to tab 1–8',
    'Pindah ke tab terakhir': 'Switch to last tab',
    'Cycle bahasa ID/EN/JA': 'Cycle language ID/EN/JA',
    'Tampilkan shortcut': 'Show shortcuts',
    'Tutup overlay': 'Close overlay',
    'Command palette': 'Command palette',
    'Setujui dokumen terpilih?': 'Approve selected documents?',
    'Tolak dokumen terpilih?': 'Reject selected documents?',
    'Posting dokumen terpilih?': 'Post selected documents?',
    'Hapus dokumen terpilih?': 'Delete selected documents?',
    'Export data terpilih?': 'Export selected data?',
    Setujui: 'Approve',
    Tolak: 'Reject',
    Posting: 'Post',
    Hapus: 'Delete',
    disetujui: 'approved',
    ditolak: 'rejected',
    diposting: 'posted',
    dihapus: 'deleted',
    diekspor: 'exported',
    'dokumen akan': 'documents will be',
    dokumen: 'documents',
    'Tindakan ini tidak dapat dibatalkan.': 'This action cannot be undone.',
    'Aksi tercatat di audit trail.': 'Action is logged in the audit trail.',
    'belum dibaca': 'unread',
    'Tandai semua': 'Mark all',
    Semua: 'All',
    'Belum dibaca': 'Unread',
    'Tidak ada notifikasi': 'No notifications',
    'Buka Dashboard': 'Open Dashboard',
    'kejadian hari ini': 'events today',
    Sukses: 'Success',
    'Ditolak/Batal': 'Rejected/Canceled',
    Info: 'Info',
    Edit: 'Edit',
    'Tidak ada aktivitas': 'No activity',
    'Ketik perintah atau cari...': 'Type a command or search...',
    'Tidak ada hasil': 'No results',
    navigasi: 'navigate',
    pilih: 'select',
    tutup: 'close',
    Aksi: 'Actions',
    Navigasi: 'Navigation',
    'Toggle dark mode': 'Toggle dark mode',
    'Switch language (ID/EN)': 'Switch language (ID/EN/JA)',
    baris: 'rows',
    baru: 'new',
    'Export data': 'Export data',
    Tampilkan: 'Show',
    'Jumlah baris per halaman': 'Rows per page',
    'Halaman pertama': 'First page',
    'Halaman sebelumnya': 'Previous page',
    'Halaman berikutnya': 'Next page',
    'Halaman terakhir': 'Last page',
    Filter: 'Filter',
    'Reset filter': 'Reset filter',
    dari: 'of',
    'Memuat...': 'Loading...',
    Kode: 'Code',
    Status: 'Status',
    Aktif: 'Active',
    Nonaktif: 'Inactive',
    'Tidak ada hasil untuk filter ini': 'No results match this filter',
    'Tidak ada data': 'No data',
    Riwayat: 'History',
    Aktifkan: 'Activate',
    Nonaktifkan: 'Deactivate',
    'baris dipilih': 'rows selected',
    'Menyimpan...': 'Saving...',
    Simpan: 'Save',
    'Riwayat Perubahan': 'Change History',
    'akan dihapus permanen.': 'will be permanently deleted.',
    'yang dipilih akan dihapus permanen.': 'selected will be permanently deleted.',
    'yang dipilih akan': 'selected will be',
    diaktifkan: 'activated',
    dinonaktifkan: 'deactivated',
    dibuat: 'created',
    diperbarui: 'updated',
    Gagal: 'Failed',
    'Gagal menyimpan': 'Failed to save',
    'Export belum tersedia': 'Export not available yet',
    'Pilih semua': 'Select all',
    'Pilih baris': 'Select row',
    'sub division': 'sub division',
    division: 'division',
    'sub departemen': 'sub department',
    departemen: 'department',
    project: 'project',
    'cost center': 'cost center',
    Reset: 'Reset',
    Tema: 'Theme',
    'Mode terang atau gelap': 'Light or dark mode',
    'Mode Tema': 'Theme Mode',
    'Berlaku untuk seluruh aplikasi': 'Applies to the whole app',
    Terang: 'Light',
    Gelap: 'Dark',
    Bahasa: 'Language',
    Antarmuka: 'Interface',
    Indonesia: 'Indonesian',
    English: 'English',
    Japanese: 'Japanese',
    'Warna Aksen': 'Accent Color',
    'Paket & warna primer': 'Pack & primary color',
    'Paket Warna': 'Color Pack',
    'Set warna siap pakai': 'Preset color sets',
    'Warna Spesifik': 'Specific Color',
    'Aksen Aktif': 'Active Accent',
    'Ukuran Font': 'Font Size',
    'Skala teks antarmuka': 'Interface text scale',
    Ukuran: 'Size',
    'Kecil · Normal · Besar · Ekstra Besar': 'Small · Normal · Large · Extra Large',
    Kecil: 'Small',
    Normal: 'Normal',
    Besar: 'Large',
    'Ekstra Besar': 'Extra Large',
    Pratinjau: 'Preview',
    'Contoh teks tabel & form': 'Sample table & form text',
    Layout: 'Layout',
    'Kepadatan tampilan tabel & list': 'Density of tables & lists',
    Kepadatan: 'Density',
    'Compact memuat lebih banyak baris': 'Compact fits more rows',
    Compact: 'Compact',
    Comfortable: 'Comfortable',
    'Menu Sidebar': 'Sidebar Menu',
    'Template navigasi samping': 'Side navigation template',
    Template: 'Template',
    'Ikon saja atau dengan label teks': 'Icon only or with text label',
    Ikon: 'Icon',
    'Ikon + Label': 'Icon + Label',
    'Setting · Tampilan': 'Settings · Appearance',
    Tampilan_status: 'Theme {theme} · {primary} · font {fontScale} · {density} · sidebar {sidebar}',
    'Tampilan dikembalikan ke bawaan': 'Appearance reset to defaults',
    'Gagal menyimpan preferensi tampilan': 'Failed to save appearance preferences',
    'Pratinjau Langsung': 'Live Preview',
    'Perubahan diterapkan seketika': 'Changes applied instantly',
    Export: 'Export',
    No: 'No',
    Nama: 'Name',
    Total: 'Total',
    Korporat: 'Corporate',
    'Biru profesional': 'Professional blue',
    Kreatif: 'Creative',
    'Violet & fuchsia': 'Violet & fuchsia',
    Natural: 'Natural',
    'Hijau segar': 'Fresh green',
    Hangat: 'Warm',
    'Amber & rose': 'Amber & rose',
    Biru: 'Blue',
    Indigo: 'Indigo',
    Violet: 'Violet',
    Fuchsia: 'Fuchsia',
    Rose: 'Rose',
    Amber: 'Amber',
    Emerald: 'Emerald',
    Teal: 'Teal',
    Cyan: 'Cyan',
  },
  ja: {
    Dashboard: 'ダッシュボード',
    Statistik: '統計',
    'Data Master': 'マスターデータ',
    Keuangan: '財務',
    Transaksi: '取引',
    Laporan: 'レポート',
    Persediaan: '在庫',
    Pembelian: '購買',
    Sales: '販売',
    Produksi: '生産',
    'Fixed Asset': '固定資産',
    Setting: '設定',
    'Kas Masuk': '入金',
    'Kas Keluar': '出金',
    'Bank Masuk': '銀行入金',
    'Bank Keluar': '銀行出金',
    'Jurnal Umum': '一般仕訳',
    'Giro Masuk': '受取手形',
    'Giro Keluar': '支払手形',
    'Buku Besar': '総勘定元帳',
    Tambah: '新規',
    'Cari semua...': 'すべて検索...',
    'Pendapatan bulan ini': '今月の収益',
    'Pengeluaran bulan ini': '今月の支出',
    'Saldo Bank': '銀行残高',
    'Giro Outstanding': '未決済手形',
    'vs bulan lalu': '先月比',
    'Aktivitas Terbaru': '最近のアクティビティ',
    'Lihat semua': 'すべて表示',
    'Aksi Cepat': 'クイックアクション',
    Pintasan: 'ショートカット',
    'Buat Kas Masuk': '入金作成',
    'Buat Kas Keluar': '出金作成',
    'Posting Jurnal': '仕訳転記',
    'Lihat Buku Besar': '元帳を見る',
    'Cash Flow 14 Hari': '14日間キャッシュフロー',
    'Top Transaksi Hari Ini': '本日のトップ取引',
    Customer: '顧客',
    Supplier: '仕入先',
    Item: '品目',
    'Chart of Account': '勘定科目表',
    'Cabang & Lokasi': '支店・拠点',
    'Cost Center': 'コストセンター',
    'Stock Opname': '棚卸',
    'Mutasi Stok': '在庫移動',
    Penyesuaian: '調整',
    'Transfer Gudang': '倉庫間移動',
    'PO Pembelian': '発注書',
    'Penerimaan Barang': '入荷',
    'Faktur Pembelian': '仕入請求書',
    'Retur Pembelian': '仕入返品',
    'SO Penjualan': '受注書',
    Pengiriman: '出荷',
    'Faktur Penjualan': '売上請求書',
    'Retur Penjualan': '売上返品',
    'Work Order': '作業指示',
    BOM: 'BOM',
    'Output Produksi': '生産実績',
    'Daftar Aset': '資産一覧',
    Penyusutan: '減価償却',
    Disposal: '処分',
    Users: 'ユーザー',
    Roles: 'ロール',
    Preferensi: '環境設定',
    Neraca: '貸借対照表',
    'Laba Rugi': '損益計算書',
    'Arus Kas': 'キャッシュフロー',
    'Perubahan Modal': '資本変動',
    Tampilan: '外観',
    Notifikasi: '通知',
    Aktivitas: 'アクティビティ',
    'Tutup tab': 'タブを閉じる',
    'Tab baru': '新しいタブ',
    'Duplikat tab': 'タブを複製',
    'Muat ulang': '再読み込み',
    Tutup: '閉じる',
    'Tutup tab lain': '他のタブを閉じる',
    'Tutup tab di kanan': '右側のタブを閉じる',
    Administrator: '管理者',
    'Master Data': 'マスターデータ',
    'Finance & Accounting': '財務・会計',
    'Warehouse & Inventory': '倉庫・在庫',
    Purchasing: '購買',
    Production: '生産',
    'Fixed Assets': '固定資産',
    'Point of Sale': 'POS',
    'Point of Sales': 'POS',
    'HR & Payroll': '人事・給与',
    Hospital: '病院',
    Academic: '学術',
    Cooperative: '協同組合',
    Settings: '設定',
    Appearance: '外観',
    'Profil Saya': 'マイプロフィール',
    Keluar: 'ログアウト',
    Division: '部門',
    'Sub Division': 'サブ部門',
    Department: '部署',
    'Sub Department': 'サブ部署',
    Project: 'プロジェクト',
    Branch: '支店',
    Location: '拠点',
    Warehouse: '倉庫',
    Workspace: 'ワークスペース',
    'Buat Workspace': 'ワークスペースを作成',
    'Ganti workspace': 'ワークスペースを切替',
    'Hapus workspace': 'ワークスペースを削除',
    aktif: '有効',
    Konfirmasi: '確認',
    Batal: 'キャンセル',
    'Tutup tab?': 'タブを閉じますか？',
    'tab ini': 'このタブ',
    '"{label}" akan ditutup.': '"{label}" を閉じます。',
    'Keyboard Shortcuts': 'キーボードショートカット',
    'Buka command palette': 'コマンドパレットを開く',
    'Tutup tab aktif': 'アクティブなタブを閉じる',
    'Pindah ke tab 1–8': 'タブ 1–8 に切替',
    'Pindah ke tab terakhir': '最後のタブに切替',
    'Cycle bahasa ID/EN/JA': '言語切替 ID/EN/JA',
    'Tampilkan shortcut': 'ショートカットを表示',
    'Tutup overlay': 'オーバーレイを閉じる',
    'Command palette': 'コマンドパレット',
    'Setujui dokumen terpilih?': '選択した文書を承認しますか？',
    'Tolak dokumen terpilih?': '選択した文書を却下しますか？',
    'Posting dokumen terpilih?': '選択した文書を転記しますか？',
    'Hapus dokumen terpilih?': '選択した文書を削除しますか？',
    'Export data terpilih?': '選択したデータをエクスポートしますか？',
    Setujui: '承認',
    Tolak: '却下',
    Posting: '転記',
    Hapus: '削除',
    disetujui: '承認済み',
    ditolak: '却下済み',
    diposting: '転記済み',
    dihapus: '削除済み',
    diekspor: 'エクスポート済み',
    'dokumen akan': '件の文書を',
    dokumen: '件の文書',
    'Tindakan ini tidak dapat dibatalkan.': 'この操作は取り消せません。',
    'Aksi tercatat di audit trail.': '操作は監査ログに記録されます。',
    'belum dibaca': '未読',
    'Tandai semua': 'すべて既読',
    Semua: 'すべて',
    'Belum dibaca': '未読',
    'Tidak ada notifikasi': '通知はありません',
    'Buka Dashboard': 'ダッシュボードを開く',
    'kejadian hari ini': '件のイベント',
    Sukses: '成功',
    'Ditolak/Batal': '却下／キャンセル',
    Info: '情報',
    Edit: '編集',
    'Tidak ada aktivitas': 'アクティビティはありません',
    'Ketik perintah atau cari...': 'コマンドを入力または検索...',
    'Tidak ada hasil': '結果がありません',
    navigasi: '移動',
    pilih: '選択',
    tutup: '閉じる',
    Aksi: 'アクション',
    Navigasi: 'ナビゲーション',
    'Toggle dark mode': 'ダークモード切替',
    'Switch language (ID/EN)': '言語切替 (ID/EN/JA)',
    baris: '行',
    baru: '新規',
    'Export data': 'データをエクスポート',
    Tampilkan: '表示',
    'Jumlah baris per halaman': 'ページあたりの行数',
    'Halaman pertama': '最初のページ',
    'Halaman sebelumnya': '前のページ',
    'Halaman berikutnya': '次のページ',
    'Halaman terakhir': '最後のページ',
    Filter: 'フィルター',
    'Reset filter': 'フィルターをリセット',
    dari: '／',
    'Memuat...': '読み込み中...',
    Kode: 'コード',
    Status: 'ステータス',
    Aktif: '有効',
    Nonaktif: '無効',
    'Tidak ada hasil untuk filter ini': 'このフィルターに一致する結果はありません',
    'Tidak ada data': 'データがありません',
    Riwayat: '履歴',
    Aktifkan: '有効化',
    Nonaktifkan: '無効化',
    'baris dipilih': '行を選択中',
    'Menyimpan...': '保存中...',
    Simpan: '保存',
    'Riwayat Perubahan': '変更履歴',
    'akan dihapus permanen.': 'は完全に削除されます。',
    'yang dipilih akan dihapus permanen.': 'は完全に削除されます。',
    'yang dipilih akan': 'は',
    diaktifkan: '有効化されました',
    dinonaktifkan: '無効化されました',
    dibuat: '作成されました',
    diperbarui: '更新されました',
    Gagal: '失敗',
    'Gagal menyimpan': '保存に失敗しました',
    'Export belum tersedia': 'エクスポートはまだ利用できません',
    'Pilih semua': 'すべて選択',
    'Pilih baris': '行を選択',
    'sub division': 'サブ部門',
    division: '部門',
    'sub departemen': 'サブ部署',
    departemen: '部署',
    project: 'プロジェクト',
    'cost center': 'コストセンター',
    Reset: 'リセット',
    Tema: 'テーマ',
    'Mode terang atau gelap': 'ライトまたはダークモード',
    'Mode Tema': 'テーマモード',
    'Berlaku untuk seluruh aplikasi': 'アプリ全体に適用',
    Terang: 'ライト',
    Gelap: 'ダーク',
    Bahasa: '言語',
    Antarmuka: 'インターフェース',
    Indonesia: 'インドネシア語',
    English: '英語',
    Japanese: '日本語',
    'Warna Aksen': 'アクセントカラー',
    'Paket & warna primer': 'パック・プライマリーカラー',
    'Paket Warna': 'カラーパック',
    'Set warna siap pakai': 'プリセットカラー',
    'Warna Spesifik': '個別カラー',
    'Aksen Aktif': '有効なアクセント',
    'Ukuran Font': 'フォントサイズ',
    'Skala teks antarmuka': 'UIテキストスケール',
    Ukuran: 'サイズ',
    'Kecil · Normal · Besar · Ekstra Besar': '小 · 標準 · 大 · 特大',
    Kecil: '小',
    Normal: '標準',
    Besar: '大',
    'Ekstra Besar': '特大',
    Pratinjau: 'プレビュー',
    'Contoh teks tabel & form': 'テーブル・フォームのサンプルテキスト',
    Layout: 'レイアウト',
    'Kepadatan tampilan tabel & list': 'テーブル・リストの密度',
    Kepadatan: '密度',
    'Compact memuat lebih banyak baris': 'コンパクトで行数を増やす',
    Compact: 'コンパクト',
    Comfortable: 'ゆったり',
    'Menu Sidebar': 'サイドバーメニュー',
    'Template navigasi samping': 'サイドナビのテンプレート',
    Template: 'テンプレート',
    'Ikon saja atau dengan label teks': 'アイコンのみ／ラベル付き',
    Ikon: 'アイコン',
    'Ikon + Label': 'アイコン + ラベル',
    'Setting · Tampilan': '設定 · 外観',
    Tampilan_status: 'テーマ {theme} · {primary} · フォント {fontScale} · {density} · サイドバー {sidebar}',
    'Tampilan dikembalikan ke bawaan': '外観をデフォルトに戻しました',
    'Gagal menyimpan preferensi tampilan': '外観設定の保存に失敗しました',
    'Pratinjau Langsung': 'ライブプレビュー',
    'Perubahan diterapkan seketika': '変更は即時反映されます',
    Export: 'エクスポート',
    No: 'No',
    Nama: '名称',
    Total: '合計',
    Korporat: 'コーポレート',
    'Biru profesional': 'プロフェッショナル・ブルー',
    Kreatif: 'クリエイティブ',
    'Violet & fuchsia': 'バイオレット・フューシャ',
    Natural: 'ナチュラル',
    'Hijau segar': 'フレッシュグリーン',
    Hangat: 'ウォーム',
    'Amber & rose': 'アンバー・ローズ',
    Biru: 'ブルー',
    Indigo: 'インディゴ',
    Violet: 'バイオレット',
    Fuchsia: 'フューシャ',
    Rose: 'ローズ',
    Amber: 'アンバー',
    Emerald: 'エメラルド',
    Teal: 'ティール',
    Cyan: 'シアン',
    // --- Sidebar menu titles (seeded English → JA) ---
    'Initial Setup': '初期設定',
    Administration: '管理',
    System: 'システム',
    Organization: '組織',
    Items: '品目',
    'Item Categories': '品目カテゴリ',
    'Item Types': '品目タイプ',
    Units: '単位',
    'Item Locations': '品目所在',
    'Item Information': '品目情報',
    'Product Class': '製品クラス',
    'Price Index': '価格指数',
    'Price Category': '価格カテゴリ',
    Commission: 'コミッション',
    'Item Transaction Types': '在庫調整タイプ',
    'Stock Adjustment Type': '在庫調整タイプ',
    'Stock Adjustment Types': '在庫調整タイプ',
    'Item Permissions': '品目権限',
    Brand: 'ブランド',
    Color: '色',
    Size: 'サイズ',
    Section: 'セクション',
    Class: 'クラス',
    'Sub Class': 'サブクラス',
    Model: 'モデル',
    Designer: 'デザイナー',
    Material: '材料',
    Reference: 'リファレンス',
    Vendor: 'ベンダー',
    Miscellaneous: 'その他',
    'Customer Categories': '顧客カテゴリ',
    'Supplier Categories': '仕入先カテゴリ',
    'Partner Categories': '取引先カテゴリ',
    Partners: '取引先',
    'Salesman Categories': '営業員カテゴリ',
    Bank: '銀行',
    Expedition: '配送',
    City: '市',
    Province: '県',
    Country: '国',
    Currencies: '通貨',
    Taxes: '税',
    'Payment Terms': '支払条件',
    'Tax Settings': '税設定',
    'Document Numbering': '文書採番',
    'Fiscal Periods': '会計期間',
    'Approval Settings': '承認設定',
    'Audit Log': '監査ログ',
    'Online Users': 'オンラインユーザー',
    'User Log': 'ユーザーログ',
    'Close Fiscal Period': '会計期間締め',
    'Recalculate COGS': '原価再計算',
    'Repost Journals': '仕訳再転記',
    'Data Validity Check': 'データ整合性チェック',
    'Menu Manager': 'メニュー管理',
    'Settings Manager': '設定管理',
    'Bank Accounts': '銀行口座',
    'Description Presets': '説明プリセット',
    'Format Settings': 'フォーマット設定',
    'Default Settings': 'デフォルト設定',
    'Report Defaults': 'レポートデフォルト',
    'Signature Settings': '署名設定',
    Options: 'オプション',
    'Home Layout': 'ホームレイアウト',
    'Import Data': 'データインポート',
    'Company Settings': '会社設定',
    'Accounting Settings': '会計設定',
    'User Management': 'ユーザー管理',
    'Role Management': 'ロール管理',
    Permissions: '権限',
    Language: '言語',
    'Chart of Accounts': '勘定科目表',
    'Finance Masters': '財務マスター',
    'AR Receipts': '売掛回収',
    'AP Payments': '買掛支払',
    'Journal Entries': '仕訳',
    'General Ledger': '総勘定元帳',
    Giros: '手形',
    'Production Activity': '生産活動',
    'Production Categories': '生産カテゴリ',
    'Production Route': '生産ルート',
    'Work Estimate': '作業見積',
    Labor: '労務',
    Machine: '機械',
    'Other Costs': 'その他費用',
    Transactions: '取引',
    Reports: 'レポート',
    'Transaction Notes': '取引メモ',
    'Txn Note Detail': 'メモ詳細',
    Area: 'エリア',
    'Point Categories': 'ポイントカテゴリ',
  },
};

export type Translator = (key: string) => string;

export function makeTranslator(lang: Lang): Translator {
  return (key: string) => I18N[lang]?.[key] ?? key;
}

// ---------------------------------------------------------------------------
// Global current-language registry.
//
// Used by helpers that live outside React's component tree (toasts, confirm
// dialog, `bulkAction`) so they can translate without prop-drilling `t`.
// The app shell calls `setCurrentLang(lang)` whenever the user switches
// language; everywhere else reads via `tGlobal(key)`.
// ---------------------------------------------------------------------------

let CURRENT_LANG: Lang = 'id';

export function setCurrentLang(lang: Lang): void {
  CURRENT_LANG = lang;
}

export function getCurrentLang(): Lang {
  return CURRENT_LANG;
}

export function tGlobal(key: string): string {
  return I18N[CURRENT_LANG]?.[key] ?? key;
}
