/**
 * Seed data Indonesia lengkap untuk md-legacy-batch:
 * Country (195 — seluruh dunia, ISO 3166-1 alpha-2), Province (38 ID termasuk 4 pemekaran Papua 2022), City/Kabupaten (514 per BPS), Bank (57 — BUMN/swasta/syariah/BPD/digital/asing), Expedition (30 — nasional/on-demand/internasional).
 * Idempotent via upsert on `code`. Kode kota = kode BPS 4-digit.
 */
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  // Countries — 195 negara ISO 3166-1 alpha-2
  const countries = [
    // Asia Tenggara
    { code: 'ID', name: 'Indonesia', isoCode: 'ID' },
    { code: 'SG', name: 'Singapore', isoCode: 'SG' },
    { code: 'MY', name: 'Malaysia', isoCode: 'MY' },
    { code: 'TH', name: 'Thailand', isoCode: 'TH' },
    { code: 'PH', name: 'Philippines', isoCode: 'PH' },
    { code: 'VN', name: 'Vietnam', isoCode: 'VN' },
    { code: 'MM', name: 'Myanmar', isoCode: 'MM' },
    { code: 'KH', name: 'Cambodia', isoCode: 'KH' },
    { code: 'LA', name: 'Laos', isoCode: 'LA' },
    { code: 'BN', name: 'Brunei', isoCode: 'BN' },
    { code: 'TL', name: 'Timor-Leste', isoCode: 'TL' },
    // Asia Selatan
    { code: 'IN', name: 'India', isoCode: 'IN' },
    { code: 'PK', name: 'Pakistan', isoCode: 'PK' },
    { code: 'BD', name: 'Bangladesh', isoCode: 'BD' },
    { code: 'LK', name: 'Sri Lanka', isoCode: 'LK' },
    { code: 'NP', name: 'Nepal', isoCode: 'NP' },
    { code: 'BT', name: 'Bhutan', isoCode: 'BT' },
    { code: 'MV', name: 'Maldives', isoCode: 'MV' },
    { code: 'AF', name: 'Afghanistan', isoCode: 'AF' },
    // Asia Timur
    { code: 'CN', name: 'China', isoCode: 'CN' },
    { code: 'JP', name: 'Japan', isoCode: 'JP' },
    { code: 'KR', name: 'South Korea', isoCode: 'KR' },
    { code: 'KP', name: 'North Korea', isoCode: 'KP' },
    { code: 'TW', name: 'Taiwan', isoCode: 'TW' },
    { code: 'MN', name: 'Mongolia', isoCode: 'MN' },
    // Asia Tengah
    { code: 'KZ', name: 'Kazakhstan', isoCode: 'KZ' },
    { code: 'UZ', name: 'Uzbekistan', isoCode: 'UZ' },
    { code: 'TM', name: 'Turkmenistan', isoCode: 'TM' },
    { code: 'TJ', name: 'Tajikistan', isoCode: 'TJ' },
    { code: 'KG', name: 'Kyrgyzstan', isoCode: 'KG' },
    // Asia Barat (Timur Tengah)
    { code: 'SA', name: 'Saudi Arabia', isoCode: 'SA' },
    { code: 'AE', name: 'United Arab Emirates', isoCode: 'AE' },
    { code: 'QA', name: 'Qatar', isoCode: 'QA' },
    { code: 'KW', name: 'Kuwait', isoCode: 'KW' },
    { code: 'BH', name: 'Bahrain', isoCode: 'BH' },
    { code: 'OM', name: 'Oman', isoCode: 'OM' },
    { code: 'YE', name: 'Yemen', isoCode: 'YE' },
    { code: 'IQ', name: 'Iraq', isoCode: 'IQ' },
    { code: 'IR', name: 'Iran', isoCode: 'IR' },
    { code: 'SY', name: 'Syria', isoCode: 'SY' },
    { code: 'LB', name: 'Lebanon', isoCode: 'LB' },
    { code: 'JO', name: 'Jordan', isoCode: 'JO' },
    { code: 'IL', name: 'Israel', isoCode: 'IL' },
    { code: 'PS', name: 'Palestine', isoCode: 'PS' },
    { code: 'TR', name: 'Turkey', isoCode: 'TR' },
    { code: 'CY', name: 'Cyprus', isoCode: 'CY' },
    { code: 'AM', name: 'Armenia', isoCode: 'AM' },
    { code: 'AZ', name: 'Azerbaijan', isoCode: 'AZ' },
    { code: 'GE', name: 'Georgia', isoCode: 'GE' },
    // Eropa Barat
    { code: 'GB', name: 'United Kingdom', isoCode: 'GB' },
    { code: 'DE', name: 'Germany', isoCode: 'DE' },
    { code: 'FR', name: 'France', isoCode: 'FR' },
    { code: 'IT', name: 'Italy', isoCode: 'IT' },
    { code: 'ES', name: 'Spain', isoCode: 'ES' },
    { code: 'PT', name: 'Portugal', isoCode: 'PT' },
    { code: 'NL', name: 'Netherlands', isoCode: 'NL' },
    { code: 'BE', name: 'Belgium', isoCode: 'BE' },
    { code: 'LU', name: 'Luxembourg', isoCode: 'LU' },
    { code: 'CH', name: 'Switzerland', isoCode: 'CH' },
    { code: 'AT', name: 'Austria', isoCode: 'AT' },
    { code: 'IE', name: 'Ireland', isoCode: 'IE' },
    { code: 'IS', name: 'Iceland', isoCode: 'IS' },
    { code: 'NO', name: 'Norway', isoCode: 'NO' },
    { code: 'SE', name: 'Sweden', isoCode: 'SE' },
    { code: 'DK', name: 'Denmark', isoCode: 'DK' },
    { code: 'FI', name: 'Finland', isoCode: 'FI' },
    { code: 'LI', name: 'Liechtenstein', isoCode: 'LI' },
    { code: 'MC', name: 'Monaco', isoCode: 'MC' },
    { code: 'SM', name: 'San Marino', isoCode: 'SM' },
    { code: 'VA', name: 'Vatican City', isoCode: 'VA' },
    { code: 'AD', name: 'Andorra', isoCode: 'AD' },
    { code: 'MT', name: 'Malta', isoCode: 'MT' },
    // Eropa Timur & Tengah
    { code: 'PL', name: 'Poland', isoCode: 'PL' },
    { code: 'CZ', name: 'Czech Republic', isoCode: 'CZ' },
    { code: 'SK', name: 'Slovakia', isoCode: 'SK' },
    { code: 'HU', name: 'Hungary', isoCode: 'HU' },
    { code: 'RO', name: 'Romania', isoCode: 'RO' },
    { code: 'BG', name: 'Bulgaria', isoCode: 'BG' },
    { code: 'HR', name: 'Croatia', isoCode: 'HR' },
    { code: 'SI', name: 'Slovenia', isoCode: 'SI' },
    { code: 'BA', name: 'Bosnia and Herzegovina', isoCode: 'BA' },
    { code: 'RS', name: 'Serbia', isoCode: 'RS' },
    { code: 'ME', name: 'Montenegro', isoCode: 'ME' },
    { code: 'MK', name: 'North Macedonia', isoCode: 'MK' },
    { code: 'AL', name: 'Albania', isoCode: 'AL' },
    { code: 'XK', name: 'Kosovo', isoCode: 'XK' },
    { code: 'GR', name: 'Greece', isoCode: 'GR' },
    { code: 'RU', name: 'Russia', isoCode: 'RU' },
    { code: 'UA', name: 'Ukraine', isoCode: 'UA' },
    { code: 'BY', name: 'Belarus', isoCode: 'BY' },
    { code: 'MD', name: 'Moldova', isoCode: 'MD' },
    { code: 'EE', name: 'Estonia', isoCode: 'EE' },
    { code: 'LV', name: 'Latvia', isoCode: 'LV' },
    { code: 'LT', name: 'Lithuania', isoCode: 'LT' },
    // Amerika Utara & Karibia
    { code: 'US', name: 'United States', isoCode: 'US' },
    { code: 'CA', name: 'Canada', isoCode: 'CA' },
    { code: 'MX', name: 'Mexico', isoCode: 'MX' },
    { code: 'GT', name: 'Guatemala', isoCode: 'GT' },
    { code: 'BZ', name: 'Belize', isoCode: 'BZ' },
    { code: 'HN', name: 'Honduras', isoCode: 'HN' },
    { code: 'SV', name: 'El Salvador', isoCode: 'SV' },
    { code: 'NI', name: 'Nicaragua', isoCode: 'NI' },
    { code: 'CR', name: 'Costa Rica', isoCode: 'CR' },
    { code: 'PA', name: 'Panama', isoCode: 'PA' },
    { code: 'CU', name: 'Cuba', isoCode: 'CU' },
    { code: 'JM', name: 'Jamaica', isoCode: 'JM' },
    { code: 'HT', name: 'Haiti', isoCode: 'HT' },
    { code: 'DO', name: 'Dominican Republic', isoCode: 'DO' },
    { code: 'TT', name: 'Trinidad and Tobago', isoCode: 'TT' },
    { code: 'BS', name: 'Bahamas', isoCode: 'BS' },
    { code: 'BB', name: 'Barbados', isoCode: 'BB' },
    { code: 'GD', name: 'Grenada', isoCode: 'GD' },
    { code: 'LC', name: 'Saint Lucia', isoCode: 'LC' },
    { code: 'VC', name: 'Saint Vincent and the Grenadines', isoCode: 'VC' },
    { code: 'AG', name: 'Antigua and Barbuda', isoCode: 'AG' },
    { code: 'KN', name: 'Saint Kitts and Nevis', isoCode: 'KN' },
    { code: 'DM', name: 'Dominica', isoCode: 'DM' },
    // Amerika Selatan
    { code: 'BR', name: 'Brazil', isoCode: 'BR' },
    { code: 'AR', name: 'Argentina', isoCode: 'AR' },
    { code: 'CL', name: 'Chile', isoCode: 'CL' },
    { code: 'CO', name: 'Colombia', isoCode: 'CO' },
    { code: 'PE', name: 'Peru', isoCode: 'PE' },
    { code: 'VE', name: 'Venezuela', isoCode: 'VE' },
    { code: 'EC', name: 'Ecuador', isoCode: 'EC' },
    { code: 'BO', name: 'Bolivia', isoCode: 'BO' },
    { code: 'PY', name: 'Paraguay', isoCode: 'PY' },
    { code: 'UY', name: 'Uruguay', isoCode: 'UY' },
    { code: 'GY', name: 'Guyana', isoCode: 'GY' },
    { code: 'SR', name: 'Suriname', isoCode: 'SR' },
    // Afrika Utara
    { code: 'EG', name: 'Egypt', isoCode: 'EG' },
    { code: 'LY', name: 'Libya', isoCode: 'LY' },
    { code: 'TN', name: 'Tunisia', isoCode: 'TN' },
    { code: 'DZ', name: 'Algeria', isoCode: 'DZ' },
    { code: 'MA', name: 'Morocco', isoCode: 'MA' },
    { code: 'SD', name: 'Sudan', isoCode: 'SD' },
    { code: 'MR', name: 'Mauritania', isoCode: 'MR' },
    // Afrika Barat
    { code: 'SN', name: 'Senegal', isoCode: 'SN' },
    { code: 'GM', name: 'Gambia', isoCode: 'GM' },
    { code: 'GW', name: 'Guinea-Bissau', isoCode: 'GW' },
    { code: 'GN', name: 'Guinea', isoCode: 'GN' },
    { code: 'SL', name: 'Sierra Leone', isoCode: 'SL' },
    { code: 'LR', name: 'Liberia', isoCode: 'LR' },
    { code: 'CI', name: 'Ivory Coast', isoCode: 'CI' },
    { code: 'GH', name: 'Ghana', isoCode: 'GH' },
    { code: 'TG', name: 'Togo', isoCode: 'TG' },
    { code: 'BJ', name: 'Benin', isoCode: 'BJ' },
    { code: 'NG', name: 'Nigeria', isoCode: 'NG' },
    { code: 'NE', name: 'Niger', isoCode: 'NE' },
    { code: 'BF', name: 'Burkina Faso', isoCode: 'BF' },
    { code: 'ML', name: 'Mali', isoCode: 'ML' },
    { code: 'CV', name: 'Cape Verde', isoCode: 'CV' },
    // Afrika Tengah
    { code: 'CM', name: 'Cameroon', isoCode: 'CM' },
    { code: 'TD', name: 'Chad', isoCode: 'TD' },
    { code: 'CF', name: 'Central African Republic', isoCode: 'CF' },
    { code: 'CG', name: 'Congo', isoCode: 'CG' },
    { code: 'CD', name: 'Congo, Democratic Republic', isoCode: 'CD' },
    { code: 'GQ', name: 'Equatorial Guinea', isoCode: 'GQ' },
    { code: 'GA', name: 'Gabon', isoCode: 'GA' },
    { code: 'ST', name: 'São Tomé and Príncipe', isoCode: 'ST' },
    { code: 'BI', name: 'Burundi', isoCode: 'BI' },
    { code: 'RW', name: 'Rwanda', isoCode: 'RW' },
    // Afrika Timur
    { code: 'ET', name: 'Ethiopia', isoCode: 'ET' },
    { code: 'ER', name: 'Eritrea', isoCode: 'ER' },
    { code: 'DJ', name: 'Djibouti', isoCode: 'DJ' },
    { code: 'SO', name: 'Somalia', isoCode: 'SO' },
    { code: 'KE', name: 'Kenya', isoCode: 'KE' },
    { code: 'TZ', name: 'Tanzania', isoCode: 'TZ' },
    { code: 'UG', name: 'Uganda', isoCode: 'UG' },
    { code: 'SS', name: 'South Sudan', isoCode: 'SS' },
    { code: 'MG', name: 'Madagascar', isoCode: 'MG' },
    { code: 'MU', name: 'Mauritius', isoCode: 'MU' },
    { code: 'SC', name: 'Seychelles', isoCode: 'SC' },
    { code: 'KM', name: 'Comoros', isoCode: 'KM' },
    // Afrika Selatan
    { code: 'ZA', name: 'South Africa', isoCode: 'ZA' },
    { code: 'ZM', name: 'Zambia', isoCode: 'ZM' },
    { code: 'ZW', name: 'Zimbabwe', isoCode: 'ZW' },
    { code: 'MW', name: 'Malawi', isoCode: 'MW' },
    { code: 'MZ', name: 'Mozambique', isoCode: 'MZ' },
    { code: 'BW', name: 'Botswana', isoCode: 'BW' },
    { code: 'NA', name: 'Namibia', isoCode: 'NA' },
    { code: 'LS', name: 'Lesotho', isoCode: 'LS' },
    { code: 'SZ', name: 'Eswatini', isoCode: 'SZ' },
    { code: 'AO', name: 'Angola', isoCode: 'AO' },
    // Oseania
    { code: 'AU', name: 'Australia', isoCode: 'AU' },
    { code: 'NZ', name: 'New Zealand', isoCode: 'NZ' },
    { code: 'PG', name: 'Papua New Guinea', isoCode: 'PG' },
    { code: 'FJ', name: 'Fiji', isoCode: 'FJ' },
    { code: 'SB', name: 'Solomon Islands', isoCode: 'SB' },
    { code: 'VU', name: 'Vanuatu', isoCode: 'VU' },
    { code: 'WS', name: 'Samoa', isoCode: 'WS' },
    { code: 'TO', name: 'Tonga', isoCode: 'TO' },
    { code: 'KI', name: 'Kiribati', isoCode: 'KI' },
    { code: 'FM', name: 'Micronesia', isoCode: 'FM' },
    { code: 'MH', name: 'Marshall Islands', isoCode: 'MH' },
    { code: 'PW', name: 'Palau', isoCode: 'PW' },
    { code: 'NR', name: 'Nauru', isoCode: 'NR' },
    { code: 'TV', name: 'Tuvalu', isoCode: 'TV' },
  ];
  for (const c of countries) {
    await prisma.erpCountry.upsert({ where: { code: c.code }, update: c, create: c });
  }
  const id = await prisma.erpCountry.findUnique({ where: { code: 'ID' } });
  if (!id) throw new Error('Indonesia seed failed');

  // Provinces (38 — termasuk 4 pemekaran Papua 2022)
  const provinces: [string, string][] = [
    ['ACE', 'Aceh'], ['SUT', 'Sumatera Utara'], ['SUB', 'Sumatera Barat'], ['RIA', 'Riau'],
    ['JAM', 'Jambi'], ['SUS', 'Sumatera Selatan'], ['BEN', 'Bengkulu'], ['LAM', 'Lampung'],
    ['KEP', 'Kep. Bangka Belitung'], ['KER', 'Kep. Riau'], ['DKI', 'DKI Jakarta'],
    ['JAB', 'Jawa Barat'], ['JAT', 'Jawa Tengah'], ['DIY', 'DI Yogyakarta'], ['JAW', 'Jawa Timur'],
    ['BAN', 'Banten'], ['BAL', 'Bali'], ['NTB', 'Nusa Tenggara Barat'], ['NTT', 'Nusa Tenggara Timur'],
    ['KAB', 'Kalimantan Barat'], ['KAT', 'Kalimantan Tengah'], ['KAS', 'Kalimantan Selatan'],
    ['KAM', 'Kalimantan Timur'], ['KAU', 'Kalimantan Utara'], ['SUL', 'Sulawesi Utara'],
    ['SUE', 'Sulawesi Tengah'], ['SLS', 'Sulawesi Selatan'], ['SLT', 'Sulawesi Tenggara'],
    ['GOR', 'Gorontalo'], ['SLB', 'Sulawesi Barat'], ['MAL', 'Maluku'], ['MAU', 'Maluku Utara'],
    ['PAP', 'Papua'], ['PAB', 'Papua Barat'],
    // Pemekaran 2022
    ['PAS', 'Papua Selatan'], ['PAT', 'Papua Tengah'], ['PAG', 'Papua Pegunungan'], ['PAD', 'Papua Barat Daya'],
  ];
  for (const [code, name] of provinces) {
    await prisma.erpProvince.upsert({
      where: { code }, update: { name, countryId: id.id }, create: { code, name, countryId: id.id },
    });
  }

  // Build province id map
  const provMap: Record<string, bigint> = {};
  for (const [code] of provinces) {
    const p = await prisma.erpProvince.findUnique({ where: { code } });
    if (p) provMap[code] = p.id;
  }

  // Cities/Kabupaten — 514 kab/kota lengkap per BPS
  // Tuple: [bpsCode 4-digit, nama, kode provinsi]
  const slugifyCity = (n: string, provCode: string) =>
    n.toUpperCase().replace(/\./g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim() + '-' + provCode;
  const cities: [string, string, string][] = [
    // Aceh (23)
    ['1101', 'Kab. Simeulue', 'ACE'], ['1102', 'Kab. Aceh Singkil', 'ACE'],
    ['1103', 'Kab. Aceh Selatan', 'ACE'], ['1104', 'Kab. Aceh Tenggara', 'ACE'],
    ['1105', 'Kab. Aceh Timur', 'ACE'], ['1106', 'Kab. Aceh Tengah', 'ACE'],
    ['1107', 'Kab. Aceh Barat', 'ACE'], ['1108', 'Kab. Aceh Besar', 'ACE'],
    ['1109', 'Kab. Pidie', 'ACE'], ['1110', 'Kab. Bireuen', 'ACE'],
    ['1111', 'Kab. Aceh Utara', 'ACE'], ['1112', 'Kab. Aceh Barat Daya', 'ACE'],
    ['1113', 'Kab. Gayo Lues', 'ACE'], ['1114', 'Kab. Aceh Tamiang', 'ACE'],
    ['1115', 'Kab. Nagan Raya', 'ACE'], ['1116', 'Kab. Aceh Jaya', 'ACE'],
    ['1117', 'Kab. Bener Meriah', 'ACE'], ['1118', 'Kab. Pidie Jaya', 'ACE'],
    ['1171', 'Kota Banda Aceh', 'ACE'], ['1172', 'Kota Sabang', 'ACE'],
    ['1173', 'Kota Langsa', 'ACE'], ['1174', 'Kota Lhokseumawe', 'ACE'],
    ['1175', 'Kota Subulussalam', 'ACE'],
    // Sumatera Utara (33)
    ['1201', 'Kab. Nias', 'SUT'], ['1202', 'Kab. Mandailing Natal', 'SUT'],
    ['1203', 'Kab. Tapanuli Selatan', 'SUT'], ['1204', 'Kab. Tapanuli Tengah', 'SUT'],
    ['1205', 'Kab. Tapanuli Utara', 'SUT'], ['1206', 'Kab. Toba', 'SUT'],
    ['1207', 'Kab. Labuhanbatu', 'SUT'], ['1208', 'Kab. Asahan', 'SUT'],
    ['1209', 'Kab. Simalungun', 'SUT'], ['1210', 'Kab. Dairi', 'SUT'],
    ['1211', 'Kab. Karo', 'SUT'], ['1212', 'Kab. Deli Serdang', 'SUT'],
    ['1213', 'Kab. Langkat', 'SUT'], ['1214', 'Kab. Nias Selatan', 'SUT'],
    ['1215', 'Kab. Humbang Hasundutan', 'SUT'], ['1216', 'Kab. Pakpak Bharat', 'SUT'],
    ['1217', 'Kab. Samosir', 'SUT'], ['1218', 'Kab. Serdang Bedagai', 'SUT'],
    ['1219', 'Kab. Batu Bara', 'SUT'], ['1220', 'Kab. Padang Lawas Utara', 'SUT'],
    ['1221', 'Kab. Padang Lawas', 'SUT'], ['1222', 'Kab. Labuhanbatu Selatan', 'SUT'],
    ['1223', 'Kab. Labuhanbatu Utara', 'SUT'], ['1224', 'Kab. Nias Utara', 'SUT'],
    ['1225', 'Kab. Nias Barat', 'SUT'],
    ['1271', 'Kota Sibolga', 'SUT'], ['1272', 'Kota Tanjungbalai', 'SUT'],
    ['1273', 'Kota Pematangsiantar', 'SUT'], ['1274', 'Kota Tebing Tinggi', 'SUT'],
    ['1275', 'Kota Medan', 'SUT'], ['1276', 'Kota Binjai', 'SUT'],
    ['1277', 'Kota Padangsidimpuan', 'SUT'], ['1278', 'Kota Gunungsitoli', 'SUT'],
    // Sumatera Barat (19)
    ['1301', 'Kab. Kepulauan Mentawai', 'SUB'], ['1302', 'Kab. Pesisir Selatan', 'SUB'],
    ['1303', 'Kab. Solok', 'SUB'], ['1304', 'Kab. Sijunjung', 'SUB'],
    ['1305', 'Kab. Tanah Datar', 'SUB'], ['1306', 'Kab. Padang Pariaman', 'SUB'],
    ['1307', 'Kab. Agam', 'SUB'], ['1308', 'Kab. Lima Puluh Kota', 'SUB'],
    ['1309', 'Kab. Pasaman', 'SUB'], ['1310', 'Kab. Solok Selatan', 'SUB'],
    ['1311', 'Kab. Dharmasraya', 'SUB'], ['1312', 'Kab. Pasaman Barat', 'SUB'],
    ['1371', 'Kota Padang', 'SUB'], ['1372', 'Kota Solok', 'SUB'],
    ['1373', 'Kota Sawahlunto', 'SUB'], ['1374', 'Kota Padang Panjang', 'SUB'],
    ['1375', 'Kota Bukittinggi', 'SUB'], ['1376', 'Kota Payakumbuh', 'SUB'],
    ['1377', 'Kota Pariaman', 'SUB'],
    // Riau (12)
    ['1401', 'Kab. Kuantan Singingi', 'RIA'], ['1402', 'Kab. Indragiri Hulu', 'RIA'],
    ['1403', 'Kab. Indragiri Hilir', 'RIA'], ['1404', 'Kab. Pelalawan', 'RIA'],
    ['1405', 'Kab. Siak', 'RIA'], ['1406', 'Kab. Kampar', 'RIA'],
    ['1407', 'Kab. Rokan Hulu', 'RIA'], ['1408', 'Kab. Bengkalis', 'RIA'],
    ['1409', 'Kab. Rokan Hilir', 'RIA'], ['1410', 'Kab. Kepulauan Meranti', 'RIA'],
    ['1471', 'Kota Pekanbaru', 'RIA'], ['1473', 'Kota Dumai', 'RIA'],
    // Jambi (11)
    ['1501', 'Kab. Kerinci', 'JAM'], ['1502', 'Kab. Merangin', 'JAM'],
    ['1503', 'Kab. Sarolangun', 'JAM'], ['1504', 'Kab. Batanghari', 'JAM'],
    ['1505', 'Kab. Muaro Jambi', 'JAM'], ['1506', 'Kab. Tanjung Jabung Timur', 'JAM'],
    ['1507', 'Kab. Tanjung Jabung Barat', 'JAM'], ['1508', 'Kab. Tebo', 'JAM'],
    ['1509', 'Kab. Bungo', 'JAM'],
    ['1571', 'Kota Jambi', 'JAM'], ['1572', 'Kota Sungai Penuh', 'JAM'],
    // Sumatera Selatan (17)
    ['1601', 'Kab. Ogan Komering Ulu', 'SUS'], ['1602', 'Kab. Ogan Komering Ilir', 'SUS'],
    ['1603', 'Kab. Muara Enim', 'SUS'], ['1604', 'Kab. Lahat', 'SUS'],
    ['1605', 'Kab. Musi Rawas', 'SUS'], ['1606', 'Kab. Musi Banyuasin', 'SUS'],
    ['1607', 'Kab. Banyuasin', 'SUS'], ['1608', 'Kab. Ogan Komering Ulu Selatan', 'SUS'],
    ['1609', 'Kab. Ogan Komering Ulu Timur', 'SUS'], ['1610', 'Kab. Ogan Ilir', 'SUS'],
    ['1611', 'Kab. Empat Lawang', 'SUS'], ['1612', 'Kab. Penukal Abab Lematang Ilir', 'SUS'],
    ['1613', 'Kab. Musi Rawas Utara', 'SUS'],
    ['1671', 'Kota Palembang', 'SUS'], ['1672', 'Kota Prabumulih', 'SUS'],
    ['1673', 'Kota Pagar Alam', 'SUS'], ['1674', 'Kota Lubuklinggau', 'SUS'],
    // Bengkulu (10)
    ['1701', 'Kab. Bengkulu Selatan', 'BEN'], ['1702', 'Kab. Rejang Lebong', 'BEN'],
    ['1703', 'Kab. Bengkulu Utara', 'BEN'], ['1704', 'Kab. Kaur', 'BEN'],
    ['1705', 'Kab. Seluma', 'BEN'], ['1706', 'Kab. Mukomuko', 'BEN'],
    ['1707', 'Kab. Lebong', 'BEN'], ['1708', 'Kab. Kepahiang', 'BEN'],
    ['1709', 'Kab. Bengkulu Tengah', 'BEN'],
    ['1771', 'Kota Bengkulu', 'BEN'],
    // Lampung (15)
    ['1801', 'Kab. Lampung Barat', 'LAM'], ['1802', 'Kab. Tanggamus', 'LAM'],
    ['1803', 'Kab. Lampung Selatan', 'LAM'], ['1804', 'Kab. Lampung Timur', 'LAM'],
    ['1805', 'Kab. Lampung Tengah', 'LAM'], ['1806', 'Kab. Lampung Utara', 'LAM'],
    ['1807', 'Kab. Way Kanan', 'LAM'], ['1808', 'Kab. Tulang Bawang', 'LAM'],
    ['1809', 'Kab. Pesawaran', 'LAM'], ['1810', 'Kab. Pringsewu', 'LAM'],
    ['1811', 'Kab. Mesuji', 'LAM'], ['1812', 'Kab. Tulang Bawang Barat', 'LAM'],
    ['1813', 'Kab. Pesisir Barat', 'LAM'],
    ['1871', 'Kota Bandar Lampung', 'LAM'], ['1872', 'Kota Metro', 'LAM'],
    // Kepulauan Bangka Belitung (7)
    ['1901', 'Kab. Bangka', 'KEP'], ['1902', 'Kab. Belitung', 'KEP'],
    ['1903', 'Kab. Bangka Barat', 'KEP'], ['1904', 'Kab. Bangka Tengah', 'KEP'],
    ['1905', 'Kab. Bangka Selatan', 'KEP'], ['1906', 'Kab. Belitung Timur', 'KEP'],
    ['1971', 'Kota Pangkalpinang', 'KEP'],
    // Kepulauan Riau (7)
    ['2101', 'Kab. Karimun', 'KER'], ['2102', 'Kab. Bintan', 'KER'],
    ['2103', 'Kab. Natuna', 'KER'], ['2104', 'Kab. Lingga', 'KER'],
    ['2105', 'Kab. Kepulauan Anambas', 'KER'],
    ['2171', 'Kota Batam', 'KER'], ['2172', 'Kota Tanjungpinang', 'KER'],
    // DKI Jakarta (6)
    ['3101', 'Kab. Kepulauan Seribu', 'DKI'],
    ['3171', 'Kota Jakarta Selatan', 'DKI'], ['3172', 'Kota Jakarta Timur', 'DKI'],
    ['3173', 'Kota Jakarta Pusat', 'DKI'], ['3174', 'Kota Jakarta Barat', 'DKI'],
    ['3175', 'Kota Jakarta Utara', 'DKI'],
    // Jawa Barat (27)
    ['3201', 'Kab. Bogor', 'JAB'], ['3202', 'Kab. Sukabumi', 'JAB'],
    ['3203', 'Kab. Cianjur', 'JAB'], ['3204', 'Kab. Bandung', 'JAB'],
    ['3205', 'Kab. Garut', 'JAB'], ['3206', 'Kab. Tasikmalaya', 'JAB'],
    ['3207', 'Kab. Ciamis', 'JAB'], ['3208', 'Kab. Kuningan', 'JAB'],
    ['3209', 'Kab. Cirebon', 'JAB'], ['3210', 'Kab. Majalengka', 'JAB'],
    ['3211', 'Kab. Sumedang', 'JAB'], ['3212', 'Kab. Indramayu', 'JAB'],
    ['3213', 'Kab. Subang', 'JAB'], ['3214', 'Kab. Purwakarta', 'JAB'],
    ['3215', 'Kab. Karawang', 'JAB'], ['3216', 'Kab. Bekasi', 'JAB'],
    ['3217', 'Kab. Bandung Barat', 'JAB'], ['3218', 'Kab. Pangandaran', 'JAB'],
    ['3271', 'Kota Bogor', 'JAB'], ['3272', 'Kota Sukabumi', 'JAB'],
    ['3273', 'Kota Bandung', 'JAB'], ['3274', 'Kota Cirebon', 'JAB'],
    ['3275', 'Kota Bekasi', 'JAB'], ['3276', 'Kota Depok', 'JAB'],
    ['3277', 'Kota Cimahi', 'JAB'], ['3278', 'Kota Tasikmalaya', 'JAB'],
    ['3279', 'Kota Banjar', 'JAB'],
    // Jawa Tengah (35)
    ['3301', 'Kab. Cilacap', 'JAT'], ['3302', 'Kab. Banyumas', 'JAT'],
    ['3303', 'Kab. Purbalingga', 'JAT'], ['3304', 'Kab. Banjarnegara', 'JAT'],
    ['3305', 'Kab. Kebumen', 'JAT'], ['3306', 'Kab. Purworejo', 'JAT'],
    ['3307', 'Kab. Wonosobo', 'JAT'], ['3308', 'Kab. Magelang', 'JAT'],
    ['3309', 'Kab. Boyolali', 'JAT'], ['3310', 'Kab. Klaten', 'JAT'],
    ['3311', 'Kab. Sukoharjo', 'JAT'], ['3312', 'Kab. Wonogiri', 'JAT'],
    ['3313', 'Kab. Karanganyar', 'JAT'], ['3314', 'Kab. Sragen', 'JAT'],
    ['3315', 'Kab. Grobogan', 'JAT'], ['3316', 'Kab. Blora', 'JAT'],
    ['3317', 'Kab. Rembang', 'JAT'], ['3318', 'Kab. Pati', 'JAT'],
    ['3319', 'Kab. Kudus', 'JAT'], ['3320', 'Kab. Jepara', 'JAT'],
    ['3321', 'Kab. Demak', 'JAT'], ['3322', 'Kab. Semarang', 'JAT'],
    ['3323', 'Kab. Temanggung', 'JAT'], ['3324', 'Kab. Kendal', 'JAT'],
    ['3325', 'Kab. Batang', 'JAT'], ['3326', 'Kab. Pekalongan', 'JAT'],
    ['3327', 'Kab. Pemalang', 'JAT'], ['3328', 'Kab. Tegal', 'JAT'],
    ['3329', 'Kab. Brebes', 'JAT'],
    ['3371', 'Kota Magelang', 'JAT'], ['3372', 'Kota Surakarta', 'JAT'],
    ['3373', 'Kota Salatiga', 'JAT'], ['3374', 'Kota Semarang', 'JAT'],
    ['3375', 'Kota Pekalongan', 'JAT'], ['3376', 'Kota Tegal', 'JAT'],
    // DI Yogyakarta (5)
    ['3401', 'Kab. Kulon Progo', 'DIY'], ['3402', 'Kab. Bantul', 'DIY'],
    ['3403', 'Kab. Gunungkidul', 'DIY'], ['3404', 'Kab. Sleman', 'DIY'],
    ['3471', 'Kota Yogyakarta', 'DIY'],
    // Jawa Timur (38)
    ['3501', 'Kab. Pacitan', 'JAW'], ['3502', 'Kab. Ponorogo', 'JAW'],
    ['3503', 'Kab. Trenggalek', 'JAW'], ['3504', 'Kab. Tulungagung', 'JAW'],
    ['3505', 'Kab. Blitar', 'JAW'], ['3506', 'Kab. Kediri', 'JAW'],
    ['3507', 'Kab. Malang', 'JAW'], ['3508', 'Kab. Lumajang', 'JAW'],
    ['3509', 'Kab. Jember', 'JAW'], ['3510', 'Kab. Banyuwangi', 'JAW'],
    ['3511', 'Kab. Bondowoso', 'JAW'], ['3512', 'Kab. Situbondo', 'JAW'],
    ['3513', 'Kab. Probolinggo', 'JAW'], ['3514', 'Kab. Pasuruan', 'JAW'],
    ['3515', 'Kab. Sidoarjo', 'JAW'], ['3516', 'Kab. Mojokerto', 'JAW'],
    ['3517', 'Kab. Jombang', 'JAW'], ['3518', 'Kab. Nganjuk', 'JAW'],
    ['3519', 'Kab. Madiun', 'JAW'], ['3520', 'Kab. Magetan', 'JAW'],
    ['3521', 'Kab. Ngawi', 'JAW'], ['3522', 'Kab. Bojonegoro', 'JAW'],
    ['3523', 'Kab. Tuban', 'JAW'], ['3524', 'Kab. Lamongan', 'JAW'],
    ['3525', 'Kab. Gresik', 'JAW'], ['3526', 'Kab. Bangkalan', 'JAW'],
    ['3527', 'Kab. Sampang', 'JAW'], ['3528', 'Kab. Pamekasan', 'JAW'],
    ['3529', 'Kab. Sumenep', 'JAW'],
    ['3571', 'Kota Kediri', 'JAW'], ['3572', 'Kota Blitar', 'JAW'],
    ['3573', 'Kota Malang', 'JAW'], ['3574', 'Kota Probolinggo', 'JAW'],
    ['3575', 'Kota Pasuruan', 'JAW'], ['3576', 'Kota Mojokerto', 'JAW'],
    ['3577', 'Kota Madiun', 'JAW'], ['3578', 'Kota Surabaya', 'JAW'],
    ['3579', 'Kota Batu', 'JAW'],
    // Banten (8)
    ['3601', 'Kab. Pandeglang', 'BAN'], ['3602', 'Kab. Lebak', 'BAN'],
    ['3603', 'Kab. Tangerang', 'BAN'], ['3604', 'Kab. Serang', 'BAN'],
    ['3671', 'Kota Tangerang', 'BAN'], ['3672', 'Kota Cilegon', 'BAN'],
    ['3673', 'Kota Serang', 'BAN'], ['3674', 'Kota Tangerang Selatan', 'BAN'],
    // Bali (9)
    ['5101', 'Kab. Jembrana', 'BAL'], ['5102', 'Kab. Tabanan', 'BAL'],
    ['5103', 'Kab. Badung', 'BAL'], ['5104', 'Kab. Gianyar', 'BAL'],
    ['5105', 'Kab. Klungkung', 'BAL'], ['5106', 'Kab. Bangli', 'BAL'],
    ['5107', 'Kab. Karangasem', 'BAL'], ['5108', 'Kab. Buleleng', 'BAL'],
    ['5171', 'Kota Denpasar', 'BAL'],
    // Nusa Tenggara Barat (10)
    ['5201', 'Kab. Lombok Barat', 'NTB'], ['5202', 'Kab. Lombok Tengah', 'NTB'],
    ['5203', 'Kab. Lombok Timur', 'NTB'], ['5204', 'Kab. Sumbawa', 'NTB'],
    ['5205', 'Kab. Dompu', 'NTB'], ['5206', 'Kab. Bima', 'NTB'],
    ['5207', 'Kab. Sumbawa Barat', 'NTB'], ['5208', 'Kab. Lombok Utara', 'NTB'],
    ['5271', 'Kota Mataram', 'NTB'], ['5272', 'Kota Bima', 'NTB'],
    // Nusa Tenggara Timur (22)
    ['5301', 'Kab. Sumba Barat', 'NTT'], ['5302', 'Kab. Sumba Timur', 'NTT'],
    ['5303', 'Kab. Kupang', 'NTT'], ['5304', 'Kab. Timor Tengah Selatan', 'NTT'],
    ['5305', 'Kab. Timor Tengah Utara', 'NTT'], ['5306', 'Kab. Belu', 'NTT'],
    ['5307', 'Kab. Alor', 'NTT'], ['5308', 'Kab. Lembata', 'NTT'],
    ['5309', 'Kab. Flores Timur', 'NTT'], ['5310', 'Kab. Sikka', 'NTT'],
    ['5311', 'Kab. Ende', 'NTT'], ['5312', 'Kab. Ngada', 'NTT'],
    ['5313', 'Kab. Manggarai', 'NTT'], ['5314', 'Kab. Rote Ndao', 'NTT'],
    ['5315', 'Kab. Manggarai Barat', 'NTT'], ['5316', 'Kab. Sumba Tengah', 'NTT'],
    ['5317', 'Kab. Sumba Barat Daya', 'NTT'], ['5318', 'Kab. Nagekeo', 'NTT'],
    ['5319', 'Kab. Manggarai Timur', 'NTT'], ['5320', 'Kab. Sabu Raijua', 'NTT'],
    ['5321', 'Kab. Malaka', 'NTT'],
    ['5371', 'Kota Kupang', 'NTT'],
    // Kalimantan Barat (14)
    ['6101', 'Kab. Sambas', 'KAB'], ['6102', 'Kab. Bengkayang', 'KAB'],
    ['6103', 'Kab. Landak', 'KAB'], ['6104', 'Kab. Mempawah', 'KAB'],
    ['6105', 'Kab. Sanggau', 'KAB'], ['6106', 'Kab. Ketapang', 'KAB'],
    ['6107', 'Kab. Sintang', 'KAB'], ['6108', 'Kab. Kapuas Hulu', 'KAB'],
    ['6109', 'Kab. Sekadau', 'KAB'], ['6110', 'Kab. Melawi', 'KAB'],
    ['6111', 'Kab. Kayong Utara', 'KAB'], ['6112', 'Kab. Kubu Raya', 'KAB'],
    ['6171', 'Kota Pontianak', 'KAB'], ['6172', 'Kota Singkawang', 'KAB'],
    // Kalimantan Tengah (14)
    ['6201', 'Kab. Kotawaringin Barat', 'KAT'], ['6202', 'Kab. Kotawaringin Timur', 'KAT'],
    ['6203', 'Kab. Kapuas', 'KAT'], ['6204', 'Kab. Barito Selatan', 'KAT'],
    ['6205', 'Kab. Barito Utara', 'KAT'], ['6206', 'Kab. Sukamara', 'KAT'],
    ['6207', 'Kab. Lamandau', 'KAT'], ['6208', 'Kab. Seruyan', 'KAT'],
    ['6209', 'Kab. Katingan', 'KAT'], ['6210', 'Kab. Pulang Pisau', 'KAT'],
    ['6211', 'Kab. Gunung Mas', 'KAT'], ['6212', 'Kab. Barito Timur', 'KAT'],
    ['6213', 'Kab. Murung Raya', 'KAT'],
    ['6271', 'Kota Palangka Raya', 'KAT'],
    // Kalimantan Selatan (13)
    ['6301', 'Kab. Tanah Laut', 'KAS'], ['6302', 'Kab. Kotabaru', 'KAS'],
    ['6303', 'Kab. Banjar', 'KAS'], ['6304', 'Kab. Barito Kuala', 'KAS'],
    ['6305', 'Kab. Tapin', 'KAS'], ['6306', 'Kab. Hulu Sungai Selatan', 'KAS'],
    ['6307', 'Kab. Hulu Sungai Tengah', 'KAS'], ['6308', 'Kab. Hulu Sungai Utara', 'KAS'],
    ['6309', 'Kab. Tabalong', 'KAS'], ['6310', 'Kab. Tanah Bumbu', 'KAS'],
    ['6311', 'Kab. Balangan', 'KAS'],
    ['6371', 'Kota Banjarmasin', 'KAS'], ['6372', 'Kota Banjarbaru', 'KAS'],
    // Kalimantan Timur (10)
    ['6401', 'Kab. Paser', 'KAM'], ['6402', 'Kab. Kutai Barat', 'KAM'],
    ['6403', 'Kab. Kutai Kartanegara', 'KAM'], ['6404', 'Kab. Kutai Timur', 'KAM'],
    ['6405', 'Kab. Berau', 'KAM'], ['6409', 'Kab. Penajam Paser Utara', 'KAM'],
    ['6411', 'Kab. Mahakam Ulu', 'KAM'],
    ['6471', 'Kota Balikpapan', 'KAM'], ['6472', 'Kota Samarinda', 'KAM'],
    ['6474', 'Kota Bontang', 'KAM'],
    // Kalimantan Utara (5)
    ['6501', 'Kab. Malinau', 'KAU'], ['6502', 'Kab. Bulungan', 'KAU'],
    ['6503', 'Kab. Nunukan', 'KAU'], ['6504', 'Kab. Tana Tidung', 'KAU'],
    ['6571', 'Kota Tarakan', 'KAU'],
    // Sulawesi Utara (15)
    ['7101', 'Kab. Bolaang Mongondow', 'SUL'], ['7102', 'Kab. Minahasa', 'SUL'],
    ['7103', 'Kab. Kepulauan Sangihe', 'SUL'], ['7104', 'Kab. Kepulauan Talaud', 'SUL'],
    ['7105', 'Kab. Minahasa Selatan', 'SUL'], ['7106', 'Kab. Minahasa Utara', 'SUL'],
    ['7107', 'Kab. Bolaang Mongondow Utara', 'SUL'], ['7108', 'Kab. Siau Tagulandang Biaro', 'SUL'],
    ['7109', 'Kab. Minahasa Tenggara', 'SUL'], ['7110', 'Kab. Bolaang Mongondow Selatan', 'SUL'],
    ['7111', 'Kab. Bolaang Mongondow Timur', 'SUL'],
    ['7171', 'Kota Manado', 'SUL'], ['7172', 'Kota Bitung', 'SUL'],
    ['7173', 'Kota Tomohon', 'SUL'], ['7174', 'Kota Kotamobagu', 'SUL'],
    // Sulawesi Tengah (13)
    ['7201', 'Kab. Banggai Kepulauan', 'SUE'], ['7202', 'Kab. Banggai', 'SUE'],
    ['7203', 'Kab. Morowali', 'SUE'], ['7204', 'Kab. Poso', 'SUE'],
    ['7205', 'Kab. Donggala', 'SUE'], ['7206', 'Kab. Toli-Toli', 'SUE'],
    ['7207', 'Kab. Buol', 'SUE'], ['7208', 'Kab. Parigi Moutong', 'SUE'],
    ['7209', 'Kab. Tojo Una-Una', 'SUE'], ['7210', 'Kab. Sigi', 'SUE'],
    ['7211', 'Kab. Banggai Laut', 'SUE'], ['7212', 'Kab. Morowali Utara', 'SUE'],
    ['7271', 'Kota Palu', 'SUE'],
    // Sulawesi Selatan (24)
    ['7301', 'Kab. Kepulauan Selayar', 'SLS'], ['7302', 'Kab. Bulukumba', 'SLS'],
    ['7303', 'Kab. Bantaeng', 'SLS'], ['7304', 'Kab. Jeneponto', 'SLS'],
    ['7305', 'Kab. Takalar', 'SLS'], ['7306', 'Kab. Gowa', 'SLS'],
    ['7307', 'Kab. Sinjai', 'SLS'], ['7308', 'Kab. Maros', 'SLS'],
    ['7309', 'Kab. Pangkajene dan Kepulauan', 'SLS'], ['7310', 'Kab. Barru', 'SLS'],
    ['7311', 'Kab. Bone', 'SLS'], ['7312', 'Kab. Soppeng', 'SLS'],
    ['7313', 'Kab. Wajo', 'SLS'], ['7314', 'Kab. Sidenreng Rappang', 'SLS'],
    ['7315', 'Kab. Pinrang', 'SLS'], ['7316', 'Kab. Enrekang', 'SLS'],
    ['7317', 'Kab. Luwu', 'SLS'], ['7318', 'Kab. Tana Toraja', 'SLS'],
    ['7322', 'Kab. Luwu Utara', 'SLS'], ['7325', 'Kab. Luwu Timur', 'SLS'],
    ['7326', 'Kab. Toraja Utara', 'SLS'],
    ['7371', 'Kota Makassar', 'SLS'], ['7372', 'Kota Parepare', 'SLS'],
    ['7373', 'Kota Palopo', 'SLS'],
    // Sulawesi Tenggara (17)
    ['7401', 'Kab. Buton', 'SLT'], ['7402', 'Kab. Muna', 'SLT'],
    ['7403', 'Kab. Konawe', 'SLT'], ['7404', 'Kab. Kolaka', 'SLT'],
    ['7405', 'Kab. Konawe Selatan', 'SLT'], ['7406', 'Kab. Bombana', 'SLT'],
    ['7407', 'Kab. Wakatobi', 'SLT'], ['7408', 'Kab. Kolaka Utara', 'SLT'],
    ['7409', 'Kab. Buton Utara', 'SLT'], ['7410', 'Kab. Konawe Utara', 'SLT'],
    ['7411', 'Kab. Kolaka Timur', 'SLT'], ['7412', 'Kab. Konawe Kepulauan', 'SLT'],
    ['7413', 'Kab. Muna Barat', 'SLT'], ['7414', 'Kab. Buton Tengah', 'SLT'],
    ['7415', 'Kab. Buton Selatan', 'SLT'],
    ['7471', 'Kota Kendari', 'SLT'], ['7472', 'Kota Bau-Bau', 'SLT'],
    // Gorontalo (6)
    ['7501', 'Kab. Boalemo', 'GOR'], ['7502', 'Kab. Gorontalo', 'GOR'],
    ['7503', 'Kab. Pohuwato', 'GOR'], ['7504', 'Kab. Bone Bolango', 'GOR'],
    ['7505', 'Kab. Gorontalo Utara', 'GOR'],
    ['7571', 'Kota Gorontalo', 'GOR'],
    // Sulawesi Barat (6)
    ['7601', 'Kab. Majene', 'SLB'], ['7602', 'Kab. Polewali Mandar', 'SLB'],
    ['7603', 'Kab. Mamasa', 'SLB'], ['7604', 'Kab. Mamuju', 'SLB'],
    ['7605', 'Kab. Pasangkayu', 'SLB'], ['7606', 'Kab. Mamuju Tengah', 'SLB'],
    // Maluku (11)
    ['8101', 'Kab. Kepulauan Tanimbar', 'MAL'], ['8102', 'Kab. Maluku Tenggara', 'MAL'],
    ['8103', 'Kab. Maluku Tengah', 'MAL'], ['8104', 'Kab. Buru', 'MAL'],
    ['8105', 'Kab. Kepulauan Aru', 'MAL'], ['8106', 'Kab. Seram Bagian Barat', 'MAL'],
    ['8107', 'Kab. Seram Bagian Timur', 'MAL'], ['8108', 'Kab. Maluku Barat Daya', 'MAL'],
    ['8109', 'Kab. Buru Selatan', 'MAL'],
    ['8171', 'Kota Ambon', 'MAL'], ['8172', 'Kota Tual', 'MAL'],
    // Maluku Utara (10)
    ['8201', 'Kab. Halmahera Barat', 'MAU'], ['8202', 'Kab. Halmahera Tengah', 'MAU'],
    ['8203', 'Kab. Kepulauan Sula', 'MAU'], ['8204', 'Kab. Halmahera Selatan', 'MAU'],
    ['8205', 'Kab. Halmahera Utara', 'MAU'], ['8206', 'Kab. Halmahera Timur', 'MAU'],
    ['8207', 'Kab. Pulau Morotai', 'MAU'], ['8208', 'Kab. Pulau Taliabu', 'MAU'],
    ['8271', 'Kota Ternate', 'MAU'], ['8272', 'Kota Tidore Kepulauan', 'MAU'],
    // Papua Barat (13)
    ['9101', 'Kab. Fakfak', 'PAB'], ['9102', 'Kab. Kaimana', 'PAB'],
    ['9103', 'Kab. Teluk Wondama', 'PAB'], ['9104', 'Kab. Teluk Bintuni', 'PAB'],
    ['9105', 'Kab. Manokwari', 'PAB'], ['9106', 'Kab. Sorong Selatan', 'PAB'],
    ['9107', 'Kab. Sorong', 'PAB'], ['9108', 'Kab. Raja Ampat', 'PAB'],
    ['9109', 'Kab. Tambrauw', 'PAB'], ['9110', 'Kab. Maybrat', 'PAB'],
    ['9111', 'Kab. Manokwari Selatan', 'PAB'], ['9112', 'Kab. Pegunungan Arfak', 'PAB'],
    ['9171', 'Kota Sorong', 'PAB'],
    // Papua (29)
    ['9401', 'Kab. Merauke', 'PAP'], ['9402', 'Kab. Jayawijaya', 'PAP'],
    ['9403', 'Kab. Jayapura', 'PAP'], ['9404', 'Kab. Nabire', 'PAP'],
    ['9408', 'Kab. Kepulauan Yapen', 'PAP'], ['9409', 'Kab. Biak Numfor', 'PAP'],
    ['9410', 'Kab. Paniai', 'PAP'], ['9411', 'Kab. Puncak Jaya', 'PAP'],
    ['9412', 'Kab. Mimika', 'PAP'], ['9413', 'Kab. Boven Digoel', 'PAP'],
    ['9414', 'Kab. Mappi', 'PAP'], ['9415', 'Kab. Asmat', 'PAP'],
    ['9416', 'Kab. Yahukimo', 'PAP'], ['9417', 'Kab. Pegunungan Bintang', 'PAP'],
    ['9418', 'Kab. Tolikara', 'PAP'], ['9419', 'Kab. Sarmi', 'PAP'],
    ['9420', 'Kab. Keerom', 'PAP'], ['9426', 'Kab. Waropen', 'PAP'],
    ['9427', 'Kab. Supiori', 'PAP'], ['9428', 'Kab. Mamberamo Raya', 'PAP'],
    ['9429', 'Kab. Nduga', 'PAP'], ['9430', 'Kab. Lanny Jaya', 'PAP'],
    ['9431', 'Kab. Mamberamo Tengah', 'PAP'], ['9432', 'Kab. Yalimo', 'PAP'],
    ['9433', 'Kab. Puncak', 'PAP'], ['9434', 'Kab. Dogiyai', 'PAP'],
    ['9435', 'Kab. Intan Jaya', 'PAP'], ['9436', 'Kab. Deiyai', 'PAP'],
    ['9471', 'Kota Jayapura', 'PAP'],
  ];

  for (const [bpsCode, name, provCode] of cities) {
    const provinceId = provMap[provCode];
    if (!provinceId) { console.warn(`Province not found: ${provCode} for ${name}`); continue; }
    const code = slugifyCity(name, provCode);
    const existing = await prisma.erpCity.findFirst({ where: { OR: [{ bpsCode }, { code }] } });
    if (existing) {
      await prisma.erpCity.update({ where: { id: existing.id }, data: { code, name, bpsCode, provinceId } });
    } else {
      await prisma.erpCity.create({ data: { code, name, bpsCode, provinceId } });
    }
  }

  // Banks — daftar lengkap bank Indonesia (BUMN, swasta nasional, syariah, BPD, digital, asing)
  const banks = [
    // Bank BUMN
    { code: 'BRI', name: 'Bank Rakyat Indonesia' },
    { code: 'MDR', name: 'Bank Mandiri' },
    { code: 'BNI', name: 'Bank Negara Indonesia' },
    { code: 'BTN', name: 'Bank Tabungan Negara' },
    // Bank Swasta Nasional
    { code: 'BCA', name: 'Bank Central Asia' },
    { code: 'CMB', name: 'CIMB Niaga' },
    { code: 'DAN', name: 'Bank Danamon Indonesia' },
    { code: 'PRM', name: 'Bank Permata' },
    { code: 'MYB', name: 'Maybank Indonesia' },
    { code: 'PNB', name: 'Bank Panin' },
    { code: 'OCB', name: 'Bank OCBC NISP' },
    { code: 'MEG', name: 'Bank Mega' },
    { code: 'BTP', name: 'Bank BTPN (Jenius)' },
    { code: 'BKP', name: 'Bank Bukopin' },
    { code: 'SNM', name: 'Bank Sinarmas' },
    { code: 'ARG', name: 'Bank Artha Graha Internasional' },
    { code: 'MYP', name: 'Bank Mayapada Internasional' },
    { code: 'NTR', name: 'Bank Nusantara Parahyangan' },
    { code: 'AGR', name: 'BRI Agroniaga' },
    { code: 'MTP', name: 'Bank Mandiri Taspen' },
    { code: 'INA', name: 'Bank Ina Perdana' },
    { code: 'WRI', name: 'Bank Woori Saudara Indonesia' },
    // Bank Syariah
    { code: 'BSI', name: 'Bank Syariah Indonesia' },
    { code: 'MML', name: 'Bank Muamalat Indonesia' },
    { code: 'BCS', name: 'BCA Syariah' },
    { code: 'PNS', name: 'Bank Panin Dubai Syariah' },
    { code: 'MGS', name: 'Bank Mega Syariah' },
    // Bank BPD (Daerah)
    { code: 'BJB', name: 'Bank BJB (Jawa Barat & Banten)' },
    { code: 'BDK', name: 'Bank DKI' },
    { code: 'BJT', name: 'Bank Jateng' },
    { code: 'BJW', name: 'Bank Jatim' },
    { code: 'BDI', name: 'Bank BPD DIY' },
    { code: 'BAC', name: 'Bank Aceh Syariah' },
    { code: 'BSU', name: 'Bank Sumut' },
    { code: 'BSB', name: 'Bank Sumsel Babel' },
    { code: 'BRL', name: 'Bank Riau Kepri Syariah' },
    { code: 'BLA', name: 'Bank Lampung' },
    { code: 'BKB', name: 'Bank Kalbar' },
    { code: 'BKS', name: 'Bank Kalsel' },
    { code: 'BKT', name: 'Bank Kaltimtara' },
    { code: 'BSL', name: 'Bank Sulselbar' },
    { code: 'BNB', name: 'Bank NTB Syariah' },
    { code: 'BBL', name: 'Bank BPD Bali' },
    { code: 'BPP', name: 'Bank Papua' },
    // Bank Digital
    { code: 'JAG', name: 'Bank Jago' },
    { code: 'NEO', name: 'Bank Neo Commerce' },
    { code: 'ALO', name: 'Allo Bank Indonesia' },
    { code: 'SEA', name: 'SeaBank Indonesia' },
    { code: 'RZA', name: 'Bank Raya Indonesia (ex-BRI Agro)' },
    // Bank Asing
    { code: 'DBS', name: 'DBS Indonesia' },
    { code: 'UOB', name: 'Bank UOB Indonesia' },
    { code: 'HSB', name: 'Bank HSBC Indonesia' },
    { code: 'CTB', name: 'Citibank Indonesia' },
    { code: 'SCB', name: 'Standard Chartered Indonesia' },
    { code: 'DTB', name: 'Deutsche Bank Indonesia' },
    { code: 'JPM', name: 'JP Morgan Chase Bank Indonesia' },
  ];
  for (const b of banks) {
    await prisma.erpBank.upsert({ where: { code: b.code }, update: b, create: b });
  }

  // Expeditions — daftar lengkap ekspedisi Indonesia + internasional
  const exps = [
    // Ekspedisi nasional utama
    { code: 'JNE', name: 'JNE Express' },
    { code: 'JNT', name: 'J&T Express' },
    { code: 'SCP', name: 'SiCepat Ekspres' },
    { code: 'POS', name: 'POS Indonesia' },
    { code: 'TIK', name: 'TIKI (Titipan Kilat)' },
    { code: 'ANT', name: 'AnterAja' },
    { code: 'NJX', name: 'Ninja Xpress' },
    { code: 'LPN', name: 'Lion Parcel' },
    { code: 'SAP', name: 'SAP Express' },
    { code: 'IDX', name: 'ID Express' },
    { code: 'SPX', name: 'Shopee Xpress (SPX)' },
    { code: 'LZX', name: 'Lazada Express (LEX)' },
    { code: 'RPX', name: 'RPX One (Repex Wahana)' },
    { code: 'WHN', name: 'Wahana Prestasi Logistik' },
    { code: 'PDL', name: 'Pandu Logistics' },
    { code: 'IND', name: 'Indah Cargo' },
    { code: 'SNC', name: 'Sentral Cargo' },
    { code: 'FRL', name: 'First Logistics' },
    { code: 'BRZ', name: 'Borzo (iDELIVER)' },
    { code: 'EMS', name: 'EMS (POS Express Mail Service)' },
    // On-demand / same-day lokal
    { code: 'GSD', name: 'GoSend (Gojek)' },
    { code: 'GBX', name: 'GrabExpress' },
    { code: 'LMV', name: 'Lalamove' },
    { code: 'DLV', name: 'Deliveree' },
    // Ekspedisi internasional
    { code: 'DHL', name: 'DHL Express' },
    { code: 'FDX', name: 'FedEx' },
    { code: 'UPS', name: 'UPS' },
    { code: 'TNT', name: 'TNT Express' },
    { code: 'ARX', name: 'Aramex' },
    { code: 'DPX', name: 'DPEX Worldwide' },
  ];
  for (const e of exps) {
    await prisma.erpExpedition.upsert({ where: { code: e.code }, update: e, create: e });
  }

  // ---- md_cost_centers — manufacturing hierarchy (idempotent)
  const CC_PARENTS = [
    { code: 'PROD', name: 'Produksi' },
    { code: 'ADM',  name: 'Administrasi & Umum' },
    { code: 'LOG',  name: 'Logistik & Pergudangan' },
    { code: 'QC',   name: 'Quality Control' },
    { code: 'MTC',  name: 'Pemeliharaan & Utilitas' },
    { code: 'MKT',  name: 'Pemasaran & Penjualan' },
    { code: 'RD',   name: 'Riset & Pengembangan' },
  ];
  const CC_CHILDREN: { code: string; name: string; parentCode: string }[] = [
    { code: 'PROD-MCH',  name: 'Pemesinan (Machining)',           parentCode: 'PROD' },
    { code: 'PROD-WLD',  name: 'Pengelasan (Welding)',            parentCode: 'PROD' },
    { code: 'PROD-FAB',  name: 'Fabrikasi (Fabrication)',         parentCode: 'PROD' },
    { code: 'PROD-ASM',  name: 'Perakitan (Assembly)',            parentCode: 'PROD' },
    { code: 'PROD-PNT',  name: 'Pengecatan (Painting)',           parentCode: 'PROD' },
    { code: 'PROD-FNS',  name: 'Finishing',                      parentCode: 'PROD' },
    { code: 'PROD-PKG',  name: 'Pengemasan (Packaging)',          parentCode: 'PROD' },
    { code: 'PROD-OVH',  name: 'Overhead Produksi',              parentCode: 'PROD' },
    { code: 'ADM-MNG',   name: 'Manajemen & Direksi',            parentCode: 'ADM'  },
    { code: 'ADM-FIN',   name: 'Keuangan & Akuntansi',           parentCode: 'ADM'  },
    { code: 'ADM-HRD',   name: 'SDM & Personalia (HRD)',         parentCode: 'ADM'  },
    { code: 'ADM-IT',    name: 'Teknologi Informasi (IT)',        parentCode: 'ADM'  },
    { code: 'ADM-LGL',   name: 'Legal & Kepatuhan',              parentCode: 'ADM'  },
    { code: 'ADM-PROC',  name: 'Pengadaan (Procurement)',        parentCode: 'ADM'  },
    { code: 'LOG-RM',    name: 'Gudang Bahan Baku',              parentCode: 'LOG'  },
    { code: 'LOG-WIP',   name: 'Gudang Barang Setengah Jadi',    parentCode: 'LOG'  },
    { code: 'LOG-FG',    name: 'Gudang Barang Jadi',             parentCode: 'LOG'  },
    { code: 'LOG-IMP',   name: 'Impor & Bea Cukai',              parentCode: 'LOG'  },
    { code: 'LOG-EXP',   name: 'Ekspor & Pengiriman',            parentCode: 'LOG'  },
    { code: 'LOG-TRN',   name: 'Transportasi & Distribusi',      parentCode: 'LOG'  },
    { code: 'QC-IQC',    name: 'Incoming Quality Control (IQC)', parentCode: 'QC'   },
    { code: 'QC-IPQC',   name: 'In-Process Quality Control',    parentCode: 'QC'   },
    { code: 'QC-OQC',    name: 'Outgoing Quality Control (OQC)', parentCode: 'QC'   },
    { code: 'QC-LAB',    name: 'Laboratorium & Pengujian',       parentCode: 'QC'   },
    { code: 'QC-CAL',    name: 'Kalibrasi Alat Ukur',            parentCode: 'QC'   },
    { code: 'MTC-MCH',   name: 'Pemeliharaan Mesin',             parentCode: 'MTC'  },
    { code: 'MTC-BLD',   name: 'Pemeliharaan Gedung',            parentCode: 'MTC'  },
    { code: 'MTC-UTL',   name: 'Utilitas (Listrik, Air, Gas)',   parentCode: 'MTC'  },
    { code: 'MTC-K3',    name: 'Keselamatan & Kesehatan Kerja (K3)', parentCode: 'MTC' },
    { code: 'MKT-DOM',   name: 'Penjualan Domestik',             parentCode: 'MKT'  },
    { code: 'MKT-EXP',   name: 'Penjualan Ekspor',              parentCode: 'MKT'  },
    { code: 'MKT-ADV',   name: 'Promosi & Iklan',               parentCode: 'MKT'  },
    { code: 'MKT-CRM',   name: 'Customer Relationship (CRM)',   parentCode: 'MKT'  },
    { code: 'RD-DES',    name: 'Desain & Engineering Produk',   parentCode: 'RD'   },
    { code: 'RD-PRO',    name: 'Pengembangan Proses',           parentCode: 'RD'   },
    { code: 'RD-INN',    name: 'Inovasi & Prototipe',           parentCode: 'RD'   },
  ];
  const ccParentMap = new Map<string, bigint>();
  for (const p of CC_PARENTS) {
    const rec = await prisma.erpCostCenter.upsert({
      where: { code: p.code },
      update: { name: p.name },
      create: { code: p.code, name: p.name, isActive: true },
    });
    ccParentMap.set(p.code, rec.id);
  }
  for (const c of CC_CHILDREN) {
    const parentId = ccParentMap.get(c.parentCode);
    await prisma.erpCostCenter.upsert({
      where: { code: c.code },
      update: { name: c.name, parentId },
      create: { code: c.code, name: c.name, parentId, isActive: true },
    });
  }

  console.log('md-legacy seed complete:', {
    countries: countries.length, provinces: provinces.length,
    cities: cities.length, banks: banks.length, exps: exps.length,
    costCenters: CC_PARENTS.length + CC_CHILDREN.length,
  });
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
