/**
 * ERP route metadata — title, group, and icon for every canonical path.
 * Extracted from nav.ts to keep that file under the 400-line limit.
 *
 * Keyed by `sys_menus.path` (the canonical route id seeded via seed-erp.ts).
 * Used by `pageMeta()` in nav.ts for breadcrumbs and tab labels.
 */

import type { IconName } from '@/components/ui/icons';
import { REGISTER_ROUTE_META } from '@/lib/registers';

export const ERP_ROUTE_META: Record<string, { group: string; title: string; icon: IconName }> = {
  '/admin/users': { group: 'Administrator', title: 'Users', icon: 'gear' },
  '/admin/roles': { group: 'Administrator', title: 'Roles', icon: 'gear' },
  '/admin/permissions': { group: 'Administrator', title: 'Permissions', icon: 'gear' },
  '/admin/menus': { group: 'Administrator', title: 'Menu Manager', icon: 'gear' },
  '/admin/grid-customization': { group: 'Administrator', title: 'Kustomisasi Grid', icon: 'layers' },
  '/admin/form-builder': { group: 'Administrator', title: 'Form Builder', icon: 'gear' },
  '/admin/report-designer': { group: 'Administrator', title: 'Report Designer', icon: 'file' },
  '/admin/settings': { group: 'Administrator', title: 'System Settings', icon: 'gear' },
  '/admin/document-numbering': { group: 'Administrator', title: 'Document Numbering', icon: 'gear' },
  '/admin/fiscal-periods': { group: 'Administrator', title: 'Fiscal Periods', icon: 'gear' },
  '/admin/audit-logs': { group: 'Administrator', title: 'Audit Log', icon: 'gear' },
  '/admin/language': { group: 'Administrator', title: 'Language', icon: 'gear' },
  '/admin/users/online': { group: 'Administrator', title: 'Online Users', icon: 'gear' },
  '/admin/fiscal-periods/close': { group: 'Administrator', title: 'Close Fiscal Period', icon: 'gear' },
  '/admin/tools/recalc-cogs': { group: 'Administrator', title: 'Recalculate COGS', icon: 'gear' },
  '/admin/tools/repost-journal': { group: 'Administrator', title: 'Repost Journals', icon: 'gear' },
  '/admin/tools/data-validity': { group: 'Administrator', title: 'Data Validity Check', icon: 'gear' },
  '/admin/preferences': { group: 'Administrator', title: 'Preferensi', icon: 'gear' },
  '/admin/settings/bank-accounts': { group: 'Administrator', title: 'Rekening Bank', icon: 'gear' },
  '/admin/settings/approval': { group: 'Administrator', title: 'Pengaturan Persetujuan', icon: 'gear' },
  '/admin/settings/doc-creation-policies': { group: 'Administrator', title: 'Kebijakan Status Dokumen', icon: 'gear' },
  '/admin/settings/home': { group: 'Administrator', title: 'Pengaturan Beranda', icon: 'gear' },
  '/admin/import': { group: 'Administrator', title: 'Import Data', icon: 'gear' },
  '/admin/account-code-format': { group: 'Administrator', title: 'Account Code Format', icon: 'calculator' },
  '/admin/number-format': { group: 'Administrator', title: 'Number Format', icon: 'calculator' },
  '/admin/date-format': { group: 'Administrator', title: 'Date Format', icon: 'calendar' },
  '/master/branches': { group: 'Data Master', title: 'Branch', icon: 'database' },
  '/master/locations': { group: 'Data Master', title: 'Location', icon: 'database' },
  '/master/warehouses': { group: 'Data Master', title: 'Warehouse', icon: 'database' },
  '/master/items': { group: 'Data Master', title: 'Item', icon: 'database' },
  '/master/item-categories': { group: 'Data Master', title: 'Item Categories', icon: 'database' },
  '/master/units': { group: 'Data Master', title: 'Units', icon: 'database' },
  '/master/partners': { group: 'Data Master', title: 'Partner', icon: 'database' },
  '/master/vendors': { group: 'Data Master', title: 'Vendor', icon: 'database' },
  '/master/partner-categories': { group: 'Data Master', title: 'Partner Categories', icon: 'database' },
  '/master/partner-types': { group: 'Data Master', title: 'Tipe Partner', icon: 'database' },
  '/master/accounts': { group: 'Data Master', title: 'Chart of Accounts', icon: 'database' },
  '/master/currencies': { group: 'Data Master', title: 'Currencies', icon: 'database' },
  '/master/taxes': { group: 'Data Master', title: 'Taxes', icon: 'database' },
  '/master/payment-terms': { group: 'Data Master', title: 'Payment Terms', icon: 'database' },
  '/master/divisions': { group: 'Data Master', title: 'Division', icon: 'database' },
  '/master/subdivisions': { group: 'Data Master', title: 'Sub Division', icon: 'database' },
  // MD legacy batch (2026-05-20)
  '/master/colors': { group: 'Data Master', title: 'Color', icon: 'database' },
  '/master/nozzles': { group: 'Data Master', title: 'Nozzle', icon: 'database' },
  '/master/oems': { group: 'Data Master', title: 'OEM', icon: 'database' },
  '/master/brands': { group: 'Data Master', title: 'Brand', icon: 'database' },
  '/master/materials': { group: 'Data Master', title: 'Material', icon: 'database' },
  '/master/models': { group: 'Data Master', title: 'Model', icon: 'database' },
  '/master/sizes': { group: 'Data Master', title: 'Size', icon: 'database' },
  '/master/sections': { group: 'Data Master', title: 'Section', icon: 'database' },
  '/master/item-types': { group: 'Data Master', title: 'Item Type', icon: 'database' },
  '/master/product-classes': { group: 'Data Master', title: 'Product Class', icon: 'database' },
  '/master/classes': { group: 'Data Master', title: 'Class', icon: 'database' },
  '/master/banks': { group: 'Data Master', title: 'Bank', icon: 'database' },
  '/master/expeditions': { group: 'Data Master', title: 'Expedition', icon: 'database' },
  '/master/other-costs': { group: 'Data Master', title: 'Other Cost', icon: 'database' },
  '/master/commissions': { group: 'Data Master', title: 'Commission', icon: 'database' },
  '/master/stock-adjustment-types': { group: 'Data Master', title: 'Stock Adjustment Type', icon: 'database' },
  '/master/item-txn-types': { group: 'Data Master', title: 'Stock Adjustment Type', icon: 'database' },
  '/master/countries': { group: 'Data Master', title: 'Country', icon: 'database' },
  '/master/provinces': { group: 'Data Master', title: 'Province', icon: 'database' },
  '/master/cities': { group: 'Data Master', title: 'City', icon: 'database' },
  '/master/areas': { group: 'Data Master', title: 'Area', icon: 'database' },
  '/master/storage-bins': { group: 'Data Master', title: 'Lokasi Gudang', icon: 'database' },
  '/master/customer-categories': { group: 'Data Master', title: 'Customer Category', icon: 'database' },
  '/master/supplier-categories': { group: 'Data Master', title: 'Supplier Category', icon: 'database' },
  '/master/salesman-categories': { group: 'Data Master', title: 'Salesman Category', icon: 'database' },
  '/master/price-categories': { group: 'Data Master', title: 'Price Category', icon: 'database' },
  '/master/transaction-notes': { group: 'Data Master', title: 'Transaction Note', icon: 'database' },
  '/master/txn-note-details': { group: 'Data Master', title: 'Txn Note Detail', icon: 'database' },
  // MD production batch (2026-05-23)
  '/master/production-categories': { group: 'Data Master', title: 'Production Category', icon: 'database' },
  '/master/point-categories': { group: 'Data Master', title: 'Point Category', icon: 'database' },
  '/master/miscellaneous': { group: 'Data Master', title: 'Miscellaneous', icon: 'database' },
  '/master/sub-classes': { group: 'Data Master', title: 'Sub Class', icon: 'database' },
  '/master/work-estimates': { group: 'Data Master', title: 'Work Estimate', icon: 'database' },
  '/master/labors': { group: 'Data Master', title: 'Labor', icon: 'database' },
  '/master/machines': { group: 'Data Master', title: 'Machine', icon: 'database' },
  '/master/designers': { group: 'Data Master', title: 'Designer', icon: 'database' },
  '/master/production-activities': { group: 'Data Master', title: 'Production Activity', icon: 'database' },
  '/master/production-routes': { group: 'Data Master', title: 'Production Route', icon: 'database' },
  '/master/price-indices': { group: 'Data Master', title: 'Price Index', icon: 'database' },
  '/master/item-info': { group: 'Data Master', title: 'Item Information', icon: 'database' },
  '/master/item-informations': { group: 'Data Master', title: 'Item Information', icon: 'database' }, // alias
  '/org/branches': { group: 'Organization', title: 'Branch', icon: 'database' },
  '/org/locations': { group: 'Organization', title: 'Location', icon: 'database' },
  '/org/warehouses': { group: 'Organization', title: 'Warehouse', icon: 'database' },
  '/org/divisions': { group: 'Organization', title: 'Division', icon: 'database' },
  '/org/sub-divisions': { group: 'Organization', title: 'Sub Division', icon: 'database' },
  '/org/projects': { group: 'Organization', title: 'Project', icon: 'database' },
  '/org/cost-centers': { group: 'Organization', title: 'Cost Center', icon: 'database' },
  '/org/departments': { group: 'Organization', title: 'Department', icon: 'database' },
  '/org/sub-departments': { group: 'Organization', title: 'Sub Department', icon: 'database' },
  '/finance/general-journals': { group: 'Finance', title: 'General Journal', icon: 'calculator' },
  '/finance/receipt-memos': { group: 'Finance', title: 'Receipt Memo', icon: 'calculator' },
  '/finance/send-memos': { group: 'Finance', title: 'Send Memo', icon: 'calculator' },
  '/finance/cash-receipts': { group: 'Finance', title: 'Cash Receipt', icon: 'calculator' },
  '/finance/bank-receipts': { group: 'Finance', title: 'Bank Receipt', icon: 'calculator' },
  '/finance/cash-disbursements': { group: 'Finance', title: 'Cash Disbursement', icon: 'calculator' },
  '/finance/bank-disbursements': { group: 'Finance', title: 'Bank Keluar', icon: 'calculator' },
  '/finance/cashbank-transfers': { group: 'Finance', title: 'Cash/Bank Transfer', icon: 'calculator' },
  '/finance/receipt-giros': { group: 'Finance', title: 'Receipt Giro', icon: 'calculator' },
  '/finance/send-giros': { group: 'Finance', title: 'Send Giro', icon: 'calculator' },
  '/finance/receipt-giro-clearings': { group: 'Finance', title: 'Receipt Giro Clearing', icon: 'calculator' },
  '/finance/send-giro-clearings': { group: 'Finance', title: 'Send Giro Clearing', icon: 'calculator' },
  '/finance/adjustment-journals': { group: 'Finance', title: 'Adjustment Journal', icon: 'calculator' },
  '/finance/memorial-journals': { group: 'Finance', title: 'Memorial Journal', icon: 'calculator' },
  '/finance/opening-balances': { group: 'Finance', title: 'Opening Balance (CoA)', icon: 'calculator' },
  '/finance/revaluations': { group: 'Finance', title: 'FX Revaluation', icon: 'calculator' },
  '/finance/ledger': { group: 'Finance', title: 'General Ledger', icon: 'calculator' },
  '/finance/trial-balance': { group: 'Finance', title: 'Trial Balance', icon: 'calculator' },
  '/finance/movement-balance': { group: 'Finance', title: 'Neraca Mutasi', icon: 'calculator' },
  '/finance/balance-sheet': { group: 'Finance', title: 'Balance Sheet', icon: 'calculator' },
  '/finance/income-statement': { group: 'Finance', title: 'Income Statement', icon: 'calculator' },
  '/finance/equity-changes': { group: 'Finance', title: 'Perubahan Modal', icon: 'calculator' },
  '/finance/cash-flow': { group: 'Finance', title: 'Cash Flow', icon: 'calculator' },
  '/finance/daily-cash-bank': { group: 'Finance', title: 'Daily Cash & Bank', icon: 'calculator' },
  '/finance/ar-card': { group: 'Finance', title: 'AR Card', icon: 'calculator' },
  '/finance/ar-aging': { group: 'Finance', title: 'AR Aging', icon: 'calculator' },
  '/finance/ap-card': { group: 'Finance', title: 'AP Card', icon: 'calculator' },
  '/finance/ap-aging': { group: 'Finance', title: 'AP Aging', icon: 'calculator' },
  '/finance/giro-maturity': { group: 'Finance', title: 'Giro Maturity', icon: 'calculator' },
  '/finance/budget-realization': { group: 'Finance', title: 'Budget vs Realization', icon: 'calculator' },
  '/sales/orders': { group: 'Sales', title: 'Sales Order', icon: 'trending-up' },
  '/sales/quotations': { group: 'Sales', title: 'Sales Quotation', icon: 'trending-up' },
  '/sales/proforma-invoices': { group: 'Sales', title: 'Proforma Invoice', icon: 'trending-up' },
  '/sales/packing-lists': { group: 'Sales', title: 'Packing List', icon: 'trending-up' },
  '/sales/delivery-orders': { group: 'Sales', title: 'Delivery Order', icon: 'trending-up' },
  '/sales/delivery-reports': { group: 'Sales', title: 'Delivery Report', icon: 'trending-up' },
  '/sales/invoices': { group: 'Sales', title: 'Sales Invoice', icon: 'trending-up' },
  '/sales/returns': { group: 'Sales', title: 'Sales Return', icon: 'trending-up' },
  '/sales/return-receipts': { group: 'Sales', title: 'Return Receipt', icon: 'trending-up' },
  '/sales/customer-advances': { group: 'Sales', title: 'Customer Advance', icon: 'trending-up' },
  '/sales/invoice-swaps': { group: 'Sales', title: 'Invoice Swap', icon: 'trending-up' },
  '/sales/payment-receipts': { group: 'Sales', title: 'Payment Receipt', icon: 'trending-up' },
  '/sales/ar-collections': { group: 'Sales', title: 'AR Collection', icon: 'trending-up' },
  '/sales/ar-payments': { group: 'Sales', title: 'AR Payment', icon: 'trending-up' },
  '/sales/opening-ar-balance': { group: 'Sales', title: 'Opening AR Balance', icon: 'trending-up' },
  '/sales/freight-receivables': { group: 'Sales', title: 'Freight Receivable', icon: 'trending-up' },
  '/warehouse/material-requests': { group: 'Warehouse', title: 'Material Request', icon: 'boxes' },
  '/warehouse/transfers': { group: 'Warehouse', title: 'Stock Transfer', icon: 'boxes' },
  '/warehouse/transfer-receipts': { group: 'Warehouse', title: 'Transfer Receipt', icon: 'boxes' },
  '/warehouse/fuel-refills': { group: 'Warehouse', title: 'Fuel Refill', icon: 'boxes' },
  '/warehouse/stock-adjustments': { group: 'Warehouse', title: 'Stock Adjustment', icon: 'boxes' },
  '/warehouse/opening-stocks': { group: 'Warehouse', title: 'Opening Stock', icon: 'boxes' },
  '/warehouse/stock-counts': { group: 'Warehouse', title: 'Stock Count', icon: 'boxes' },
  '/warehouse/price-adjustments': { group: 'Warehouse', title: 'Price Adjustment', icon: 'boxes' },
  '/warehouse/receipt-weighers': { group: 'Warehouse', title: 'Receipt Weigher', icon: 'boxes' },
  '/warehouse/daily-checks': { group: 'Warehouse', title: 'Daily Check', icon: 'boxes' },
  '/purchasing/purchase-orders': { group: 'Pembelian', title: 'Pesanan Pembelian', icon: 'shopping-cart' },
  '/purchasing/purchase-requisitions': { group: 'Pembelian', title: 'Permintaan Pembelian', icon: 'shopping-cart' },
  '/purchasing/purchase-invoices': { group: 'Pembelian', title: 'Faktur Pembelian', icon: 'shopping-cart' },
  '/purchasing/return-shipments': { group: 'Pembelian', title: 'Retur Pengiriman (DNR)', icon: 'shopping-cart' },
  '/purchasing/purchase-returns': { group: 'Pembelian', title: 'Retur Pembelian (PRT)', icon: 'shopping-cart' },
  '/purchasing/goods-receipts': { group: 'Pembelian', title: 'Penerimaan Barang (GRN)', icon: 'shopping-cart' },
  '/purchasing/rfqs': { group: 'Pembelian', title: 'Permintaan Penawaran (RFQ)', icon: 'shopping-cart' },
  '/purchasing/bid-comparisons': { group: 'Pembelian', title: 'Perbandingan Harga (BS)', icon: 'shopping-cart' },
  '/purchasing/vendor-advances': { group: 'Pembelian', title: 'Uang Muka Vendor (AP)', icon: 'shopping-cart' },
  '/purchasing/freight-payables': { group: 'Pembelian', title: 'Biaya Pengiriman Terutang (PP)', icon: 'shopping-cart' },
  '/purchasing/payment-schedules': { group: 'Pembelian', title: 'Jadwal Pembayaran (VPP)', icon: 'shopping-cart' },
  '/purchasing/vendor-payments': { group: 'Pembelian', title: 'Pembayaran Vendor (VP)', icon: 'shopping-cart' },
  '/purchasing/opening-ap-balance': { group: 'Pembelian', title: 'Saldo Awal AP', icon: 'shopping-cart' },
  '/settings/appearance': { group: 'Administrator', title: 'Appearance', icon: 'gear' },
  // Purchasing (M4) reports (2026-06-03)
  '/purchasing/reports/purchase-requisitions': { group: 'Pembelian', title: 'Laporan PR', icon: 'shopping-cart' },
  '/purchasing/reports/rfqs': { group: 'Pembelian', title: 'Laporan RFQ', icon: 'shopping-cart' },
  '/purchasing/reports/bid-comparisons': { group: 'Pembelian', title: 'Laporan BS', icon: 'shopping-cart' },
  '/purchasing/reports/purchase-orders': { group: 'Pembelian', title: 'Laporan PO', icon: 'shopping-cart' },
  '/purchasing/reports/vendor-advances': { group: 'Pembelian', title: 'Laporan AP', icon: 'shopping-cart' },
  '/purchasing/reports/goods-receipts': { group: 'Pembelian', title: 'Laporan GRN', icon: 'shopping-cart' },
  '/purchasing/reports/purchase-invoices': { group: 'Pembelian', title: 'Laporan PI', icon: 'shopping-cart' },
  '/purchasing/reports/freight-payables': { group: 'Pembelian', title: 'Laporan PP', icon: 'shopping-cart' },
  '/purchasing/reports/return-shipments': { group: 'Pembelian', title: 'Laporan DNR', icon: 'shopping-cart' },
  '/purchasing/reports/purchase-returns': { group: 'Pembelian', title: 'Laporan PRT', icon: 'shopping-cart' },
  '/purchasing/reports/payment-schedules': { group: 'Pembelian', title: 'Laporan VPP', icon: 'shopping-cart' },
  '/purchasing/reports/vendor-payments': { group: 'Pembelian', title: 'Laporan VP', icon: 'shopping-cart' },
  '/purchasing/reports/summary': { group: 'Pembelian', title: 'Ringkasan Pembelian', icon: 'shopping-cart' },
  // Sales (M5) reports (2026-06-03)
  '/sales/reports/quotations': { group: 'Sales', title: 'Sales Quotation (SQ)', icon: 'file' },
  '/sales/reports/orders': { group: 'Sales', title: 'Sales Order (SO)', icon: 'file' },
  '/sales/reports/customer-advances': { group: 'Sales', title: 'Customer Advance (AS)', icon: 'file' },
  '/sales/reports/payment-receipts': { group: 'Sales', title: 'Payment Receipt (IP)', icon: 'file' },
  '/sales/reports/proforma-invoices': { group: 'Sales', title: 'Proforma Invoice (PI)', icon: 'file' },
  '/sales/reports/packing-lists': { group: 'Sales', title: 'Packing List (PL)', icon: 'file' },
  '/sales/reports/delivery-orders': { group: 'Sales', title: 'Delivery Order (DO)', icon: 'file' },
  '/sales/reports/delivery-reports': { group: 'Sales', title: 'Delivery Report (DR)', icon: 'file' },
  '/sales/reports/invoices': { group: 'Sales', title: 'Sales Invoice (SI)', icon: 'file' },
  '/sales/reports/freight-receivables': { group: 'Sales', title: 'Freight Receivable (RP)', icon: 'file' },
  '/sales/reports/return-receipts': { group: 'Sales', title: 'Return Receipt (RNR)', icon: 'file' },
  '/sales/reports/returns': { group: 'Sales', title: 'Sales Return (SR)', icon: 'file' },
  '/sales/reports/ar-collections': { group: 'Sales', title: 'AR Collection (IC)', icon: 'file' },
  '/sales/reports/ar-payments': { group: 'Sales', title: 'AR Payment (PV)', icon: 'file' },
  '/sales/reports/invoice-swaps': { group: 'Sales', title: 'Invoice Swap (SIE)', icon: 'file' },
  '/sales/reports/opening-ar-balance': { group: 'Sales', title: 'Opening AR Balance', icon: 'file' },
  '/sales/reports/summary': { group: 'Sales', title: 'Sales Summary', icon: 'stats' },
  '/sales/reports/by-customer': { group: 'Sales', title: 'Sales by Customer', icon: 'stats' },
  '/sales/reports/by-salesman': { group: 'Sales', title: 'Sales by Salesman', icon: 'stats' },
  '/sales/reports/by-item': { group: 'Sales', title: 'Sales by Item', icon: 'stats' },
  '/sales/reports/by-project': { group: 'Sales', title: 'Sales by Project', icon: 'stats' },
  '/sales/reports/by-division': { group: 'Sales', title: 'Sales by Division', icon: 'stats' },
  '/sales/reports/by-cost-center': { group: 'Sales', title: 'Sales by Cost Center', icon: 'stats' },
  '/sales/reports/by-item-category': { group: 'Sales', title: 'Sales by Item Category', icon: 'stats' },
  '/sales/reports/revenue-collection': { group: 'Sales', title: 'Revenue & Collection', icon: 'stats' },
  '/sales/reports/by-group': { group: 'Sales', title: 'Sales by Group', icon: 'stats' },
  // Warehouse (M3) statistics (2026-06-06)
  '/warehouse/stats/kpi': { group: 'Warehouse · Statistics', title: 'KPI Warehouse', icon: 'stats' },
  '/warehouse/stats/top-revenue': { group: 'Warehouse · Statistics', title: 'Top Revenue Products', icon: 'stats' },
  '/warehouse/stats/best-selling': { group: 'Warehouse · Statistics', title: 'Best Selling Products', icon: 'stats' },
  '/warehouse/stats/most-profitable': { group: 'Warehouse · Statistics', title: 'Most Profitable Products', icon: 'stats' },
  '/warehouse/stats/below-minimum': { group: 'Warehouse · Statistics', title: 'Below Minimum Stock', icon: 'stats' },
  '/warehouse/stats/approvals': { group: 'Warehouse · Statistics', title: 'Need Approval (Warehouse)', icon: 'stats' },
  '/manufacturing/boms': { group: 'Produksi', title: 'Bill of Materials', icon: 'layers' },
  '/manufacturing/work-orders': { group: 'Produksi', title: 'Work Order', icon: 'layers' },
};

// Merge in read-only "Data" register routes (derived from register configs) so
// their breadcrumbs/tab labels resolve via pageMeta() like any other ERP route.
Object.assign(ERP_ROUTE_META, REGISTER_ROUTE_META);
